<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Nh mt khu_q</name>
   <tag></tag>
   <elementGuidId>59c1d2d8-7754-44dc-a2f6-44f02b31e864</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#search_input</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='search_input']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>3ff6b343-556f-4a03-95a1-165a7aef01d5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>a85131df-4f4a-439f-a36d-7ea1fe2085d1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>q</value>
      <webElementGuid>26ac9941-03da-4765-9af8-11824cc27102</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>search_input</value>
      <webElementGuid>4b7bd211-7582-461a-a24d-0cd575f3dce1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>title</name>
      <type>Main</type>
      <value>Tìm kiếm sản phẩm</value>
      <webElementGuid>64d805a1-2543-498d-b2bc-29eecd8de16f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>ty-search-block__input cm-hint-focused</value>
      <webElementGuid>92800522-5970-4b0d-a0f2-36cb843516eb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;search_input&quot;)</value>
      <webElementGuid>72583897-bd74-4946-8c79-ea72b7c0895a</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='search_input']</value>
      <webElementGuid>aba2212d-7429-4093-870b-6cfabb9eaff6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='tygh_main_container']/div/div/div[2]/div/div[2]/div[4]/div/form/input[9]</value>
      <webElementGuid>131e0bdf-fd49-4805-935f-5b22c1f81099</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//input[9]</value>
      <webElementGuid>c2cbb1ce-4c30-4c2b-9553-f0b86262368e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @name = 'q' and @id = 'search_input' and @title = 'Tìm kiếm sản phẩm']</value>
      <webElementGuid>6d821615-b265-420e-9f76-ef54da738afb</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
