<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>span_Kt qu tm kim</name>
   <tag></tag>
   <elementGuidId>f56742cd-d86c-416a-ad53-78116594a29b</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>span.ty-mainbox-title__left</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='tygh_main_container']/div[3]/div/div/div/div/div/h1/span</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>7068c1aa-1d84-4fd9-8ab2-29d0952ce7be</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>ty-mainbox-title__left</value>
      <webElementGuid>57349877-7527-4205-a90a-b1cf2cb8895b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Kết quả tìm kiếm</value>
      <webElementGuid>9b8db88a-9f2c-42fc-8edc-f8146672b4c0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;tygh_main_container&quot;)/div[@class=&quot;tygh-content clearfix&quot;]/div[@class=&quot;container-fluid  h-filters&quot;]/div[@class=&quot;container-fluid-row main-content-grid ypi-fix-category&quot;]/div[@class=&quot;row-fluid&quot;]/div[@class=&quot;span16 main-content-grid ypi-fix-category&quot;]/div[@class=&quot;ty-mainbox-container clearfix&quot;]/h1[@class=&quot;ty-mainbox-title&quot;]/span[@class=&quot;ty-mainbox-title__left&quot;]</value>
      <webElementGuid>9f8b2337-0c71-4599-bb64-5ee2174b1479</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='tygh_main_container']/div[3]/div/div/div/div/div/h1/span</value>
      <webElementGuid>accd218b-73e4-4934-844a-75781f58670b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='iPad Pro | Pro 9.7 cũ'])[1]/following::span[1]</value>
      <webElementGuid>dd2fc253-35b0-4d12-836f-04a25df97186</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='iPad Air | Air 2 Cũ'])[1]/following::span[1]</value>
      <webElementGuid>d6105652-aa20-463d-bb34-b47e57191216</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Sản phẩm tìm thấy: 142'])[1]/preceding::span[1]</value>
      <webElementGuid>f35318ee-051a-46cd-b2ee-14163197082e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)=''])[1]/preceding::span[2]</value>
      <webElementGuid>94903a79-b2af-4b46-a067-4023f116edf6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//h1/span</value>
      <webElementGuid>c966a548-c38d-4377-a7bc-e4814acd862a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//span[(text() = 'Kết quả tìm kiếm' or . = 'Kết quả tìm kiếm')]</value>
      <webElementGuid>ef9db74e-9239-4cf5-ad54-a7693d4033b2</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
