<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>span_Sn phm tm thy 142</name>
   <tag></tag>
   <elementGuidId>bc9cfa91-cbd2-4fa8-8c28-197d188bf9cb</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#products_search_total_found_11</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//span[@id='products_search_total_found_11']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>f49b7bd3-720a-4add-ac20-0128e04493ab</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>ty-mainbox-title__right</value>
      <webElementGuid>2f6704bd-86cb-4384-9c36-ce7b68b2f2d6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>products_search_total_found_11</value>
      <webElementGuid>6c194d27-b548-4d87-ad21-75689a467387</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Sản phẩm tìm thấy: 142</value>
      <webElementGuid>b897fed1-b52f-4bab-8014-e231e200f069</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;products_search_total_found_11&quot;)</value>
      <webElementGuid>4f6957c5-1fdb-4b59-9467-a4e9cdfeec29</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//span[@id='products_search_total_found_11']</value>
      <webElementGuid>cead91eb-739a-4833-96c6-ccacbfb793cf</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='tygh_main_container']/div[3]/div/div/div/div/div/h1/span[2]</value>
      <webElementGuid>528fa382-2eb1-4862-98d9-6e61d13e8ead</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Kết quả tìm kiếm'])[2]/following::span[1]</value>
      <webElementGuid>83a25a72-965b-4227-923b-63cc2db5a662</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='iPad Pro | Pro 9.7 cũ'])[1]/following::span[2]</value>
      <webElementGuid>3b42a978-6ca2-4804-ab75-26672be5d391</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)=''])[1]/preceding::span[1]</value>
      <webElementGuid>15b06667-763e-46a1-a911-531b1c6be236</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)=''])[1]/preceding::span[1]</value>
      <webElementGuid>2a8f8c5f-2b1a-43de-9a02-888c71cb8c92</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Sản phẩm tìm thấy: 142']/parent::*</value>
      <webElementGuid>87822fef-1d7c-47eb-befb-a6a04226648a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//span[2]</value>
      <webElementGuid>c2240419-3892-4e4a-94bc-7e693b6060d6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//span[@id = 'products_search_total_found_11' and (text() = 'Sản phẩm tìm thấy: 142' or . = 'Sản phẩm tìm thấy: 142')]</value>
      <webElementGuid>a9d22a3e-abc5-423b-a6c9-1bffd289103f</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
