<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>h4_Qu tng</name>
   <tag></tag>
   <elementGuidId>7c416fc2-9fa5-42d2-8a1b-e4adb53dcac2</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>h4.promotional-gift-title</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='product_info_update_2253224695']/h4</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>h4</value>
      <webElementGuid>c0f2d8fd-6065-42c2-b233-60bdec1605d8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>promotional-gift-title</value>
      <webElementGuid>0c899721-ca8d-495d-9b20-eacdb0e87c4f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Quà tặng:</value>
      <webElementGuid>9bb3d15f-c37d-40dd-9685-717f46f9b816</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;product_info_update_2253224695&quot;)/h4[@class=&quot;promotional-gift-title&quot;]</value>
      <webElementGuid>397fc6f6-f3f8-48c8-b7f7-0ffcfad3004f</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='product_info_update_2253224695']/h4</value>
      <webElementGuid>6dae02b7-700a-4201-8945-33c42203fed8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Màu Sắc:'])[1]/following::h4[1]</value>
      <webElementGuid>6647944f-1902-4966-b092-7cfc9ff12fef</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Tùy Chọn :'])[1]/following::h4[1]</value>
      <webElementGuid>35a64343-5880-45af-8f18-ad39b5479a84</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Sản phẩm'])[2]/preceding::h4[1]</value>
      <webElementGuid>3be40a63-c9d1-4a13-a2ce-97fcd89b09e7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Số lượng'])[2]/preceding::h4[1]</value>
      <webElementGuid>297807a1-1a43-4f3d-afc6-1489a06a9abd</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Quà tặng:']/parent::*</value>
      <webElementGuid>e8ea0667-6b63-4ac1-9de4-988e283f8980</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//h4</value>
      <webElementGuid>1c0344ae-f66b-4ab2-b7a8-3c5409e6c9c1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//h4[(text() = 'Quà tặng:' or . = 'Quà tặng:')]</value>
      <webElementGuid>065c3189-b2d5-47e8-bf60-488a6ce6ea62</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
