<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>img_Tng gi_det_img_2253224695</name>
   <tag></tag>
   <elementGuidId>7cb8e0d1-5d51-4c15-a5fb-d4324f62335a</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#det_img_2253224695</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//img[@id='det_img_2253224695']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>img</value>
      <webElementGuid>ae35d4d2-790f-485f-8c58-30299a0e1d37</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>ty-pict   cm-image lazyloaded</value>
      <webElementGuid>f8669e21-2ed7-4d4a-83a4-6e49158f8b67</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>det_img_2253224695</value>
      <webElementGuid>66f82052-c9db-4ceb-bb5f-65e467f5144d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>https://zshop.vn/images/thumbnails/230/230/detailed/174/FUJIFILM_X-M5_1-2_vw26-ef.jpg</value>
      <webElementGuid>e42c93db-4aea-4901-843c-5122285fefd4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-src</name>
      <type>Main</type>
      <value>https://zshop.vn/images/thumbnails/230/230/detailed/174/FUJIFILM_X-M5_1-2_vw26-ef.jpg</value>
      <webElementGuid>9db58218-7a6f-4bed-9a92-67f61ae7f8e8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>srcset</name>
      <type>Main</type>
      <value>https://zshop.vn/images/thumbnails/460/460/detailed/174/FUJIFILM_X-M5_1-2_vw26-ef.jpg 2x</value>
      <webElementGuid>90aede18-66bf-49ef-bbf0-613c774325f9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-srcset</name>
      <type>Main</type>
      <value>https://zshop.vn/images/thumbnails/460/460/detailed/174/FUJIFILM_X-M5_1-2_vw26-ef.jpg 2x</value>
      <webElementGuid>2587ad96-8594-4196-b263-0f5b8b0d8cbd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;det_img_2253224695&quot;)</value>
      <webElementGuid>53bb3058-19a7-4968-af55-dcca3b7e2bee</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//img[@id='det_img_2253224695']</value>
      <webElementGuid>c444933f-ba89-49f8-a912-76744867d871</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='product_image_update_2253224695']/a/img</value>
      <webElementGuid>143982ae-5d53-4515-8b8e-e66e16f7fc45</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:img</name>
      <type>Main</type>
      <value>//img[contains(@src,'https://zshop.vn/images/thumbnails/230/230/detailed/174/FUJIFILM_X-M5_1-2_vw26-ef.jpg')]</value>
      <webElementGuid>44ab0dc2-3688-4e67-878a-c9c2142737eb</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//td/div/a/img</value>
      <webElementGuid>757c92f1-8525-4102-aa27-2786289d962b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//img[@id = 'det_img_2253224695' and @src = 'https://zshop.vn/images/thumbnails/230/230/detailed/174/FUJIFILM_X-M5_1-2_vw26-ef.jpg']</value>
      <webElementGuid>8d661f9a-6876-4473-86c9-2f04698f51e1</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
