<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_M gim gi_hint_coupon_code</name>
   <tag></tag>
   <elementGuidId>22fc3491-c56f-454a-98c0-bda976a5643a</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#coupon_field</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='coupon_field']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>f6975c10-bc01-4eaf-9e77-199add2728aa</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>6e71a584-1e9f-4ef8-8615-e060edab9159</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>ty-input-text cm-hint</value>
      <webElementGuid>a0edd171-6606-4b87-b53f-4eac4ec48482</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>coupon_field</value>
      <webElementGuid>eb6e934e-3734-4717-86af-5c2edb713e08</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>hint_coupon_code</value>
      <webElementGuid>d9c25e39-bd86-407a-a687-21ab3bf72b7a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>size</name>
      <type>Main</type>
      <value>40</value>
      <webElementGuid>bc7c0ab8-30c9-4bf5-80b9-b69355199204</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>Thẻ quà tặng hoặc mã giảm giá</value>
      <webElementGuid>3f1678a9-3406-4223-9275-979c73a76aed</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;coupon_field&quot;)</value>
      <webElementGuid>42bae604-f1a0-4b41-b901-c691cc4f172c</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='coupon_field']</value>
      <webElementGuid>5b1141ee-23f8-4af8-9b65-b0a958ffecde</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='checkout_totals']/div/div/form/div/input</value>
      <webElementGuid>55ccd0c7-9fb7-4b96-a939-cfe6f867b528</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/div/div/div/div/div/div/div/form/div/input</value>
      <webElementGuid>73064963-7a68-4c53-bb2e-2f8607e697a3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @id = 'coupon_field' and @name = 'hint_coupon_code']</value>
      <webElementGuid>d9977a67-6fc3-49df-8eb5-e48da1c6e51a</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
