<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input__cart_products2253224695amount</name>
   <tag></tag>
   <elementGuidId>4fa5b265-de09-4338-8c65-19c957d41538</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#amount_2253224695</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='amount_2253224695']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>1252cb4c-6e43-4e48-83ea-684d91584892</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>dd492b3b-0921-4f04-b266-269018e4c5eb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>size</name>
      <type>Main</type>
      <value>3</value>
      <webElementGuid>09d45cd3-c9b2-412e-af90-e1a588aab1d3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>amount_2253224695</value>
      <webElementGuid>bd1f3b39-c2ac-4e9d-98bb-2466b1815db9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>cart_products[2253224695][amount]</value>
      <webElementGuid>85977bff-d4a6-43e5-bae0-45c6d114ecc7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>1</value>
      <webElementGuid>4645429d-3cb2-41b3-a53a-c3bc881fe883</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>ty-value-changer__input cm-amount</value>
      <webElementGuid>131eb4ea-2190-4e71-a2ad-a432ede302f7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-ca-min-qty</name>
      <type>Main</type>
      <value>1</value>
      <webElementGuid>3bbe4f5f-3bf9-46e8-94dc-97ffcf235b71</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;amount_2253224695&quot;)</value>
      <webElementGuid>f9757221-a8bf-4117-b708-ac913613c792</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='amount_2253224695']</value>
      <webElementGuid>8b0be40a-e009-4179-a853-48af5c36adfa</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='quantity_update_2253224695']/input[2]</value>
      <webElementGuid>3bf77e60-4100-4a42-90a6-bb7a993f0e8f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//td[4]/div/input[2]</value>
      <webElementGuid>a7b650a5-58d0-432e-8de5-6eb02b8c5640</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @id = 'amount_2253224695' and @name = 'cart_products[2253224695][amount]']</value>
      <webElementGuid>f8b7aae7-8db1-4c1f-a018-b526eb8bb8ec</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
