<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>span_25,990,000_1</name>
   <tag></tag>
   <elementGuidId>1ce418cc-7d30-40cc-905b-44721b2db73a</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#sec_product_subtotal_2253224695</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//span[@id='sec_product_subtotal_2253224695']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>be42d88b-0e05-4973-85f4-b39049e9cad5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>sec_product_subtotal_2253224695</value>
      <webElementGuid>fcbe4af2-936c-4174-ac3d-48cdc7f9345f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>price</value>
      <webElementGuid>6c3fa2f1-2c83-4011-9054-8a6471d998cb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>25,990,000</value>
      <webElementGuid>8b1a0722-9236-46d5-9253-9a99bdf5928c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;sec_product_subtotal_2253224695&quot;)</value>
      <webElementGuid>8a5a4368-6212-40b0-b2ec-f767d8b63d3f</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//span[@id='sec_product_subtotal_2253224695']</value>
      <webElementGuid>4f6f91e0-6924-494e-91f1-65c8c23d9d9e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//td[@id='price_subtotal_update_2253224695']/bdi/span</value>
      <webElementGuid>c0262604-8e78-4891-b56b-c057a59a3d1a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='đ'])[2]/following::span[1]</value>
      <webElementGuid>0ddd5eb9-7ba4-447c-82a2-a36d6a9e8275</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='đ'])[3]/preceding::span[1]</value>
      <webElementGuid>d16ce666-9fe4-4dbd-a4d3-f02857dde995</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Mã giảm giá'])[1]/preceding::span[2]</value>
      <webElementGuid>9a907cc6-83ee-4a25-a6ac-b93fe26c0a13</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//td[5]/bdi/span</value>
      <webElementGuid>ba8603c8-6a2f-4ad6-8778-e50a4788bd1f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//span[@id = 'sec_product_subtotal_2253224695' and (text() = '25,990,000' or . = '25,990,000')]</value>
      <webElementGuid>cb86d1f8-0ca5-4365-9232-09295dca11a4</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
