<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>span_Tng</name>
   <tag></tag>
   <elementGuidId>3cba5000-40a3-4aa3-af43-dcf037a2a709</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>span.ty-cart-statistic__title</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='checkout_totals']/ul/li/span</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>75e04b46-3c84-4871-b1e8-c91588597915</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>ty-cart-statistic__title</value>
      <webElementGuid>0b214f70-4517-4171-8a79-8e8088e38155</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Tổng</value>
      <webElementGuid>63c5918c-60b8-456a-808c-711d82cf010e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;checkout_totals&quot;)/ul[@class=&quot;ty-cart-statistic ty-statistic-list&quot;]/li[@class=&quot;ty-cart-statistic__item ty-statistic-list-subtotal&quot;]/span[@class=&quot;ty-cart-statistic__title&quot;]</value>
      <webElementGuid>c64c2967-40ab-418d-b039-c5ac581cfceb</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='checkout_totals']/ul/li/span</value>
      <webElementGuid>4a14174e-0332-485d-bc15-dce5d22f5b6e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Áp dụng'])[1]/following::span[1]</value>
      <webElementGuid>c9f973b8-53b6-4595-b0aa-27d2d7f458fd</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Mã giảm giá'])[1]/following::span[1]</value>
      <webElementGuid>91a9325e-52db-439c-ae45-b4c44f01d38d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Tổng chi phí'])[1]/preceding::span[3]</value>
      <webElementGuid>cab4125d-7ecf-43c9-858a-26b1107af3ad</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Tổng']/parent::*</value>
      <webElementGuid>35a9b6f3-2d71-459c-8ccb-8ffe502d5398</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//li/span</value>
      <webElementGuid>7d2d4651-2f67-4cb4-ba02-729e2c81da54</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//span[(text() = 'Tổng' or . = 'Tổng')]</value>
      <webElementGuid>13ec889d-572f-4f92-8839-e8fc66e03bfb</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
