<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>span_25,990,000</name>
   <tag></tag>
   <elementGuidId>535c080d-71b1-4f5d-9b5c-19d5292c47e6</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#sec_product_price_2253224695</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//span[@id='sec_product_price_2253224695']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>ef679ff8-3193-4adb-9611-37fac50f8676</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>sec_product_price_2253224695</value>
      <webElementGuid>3f740a5e-88b9-4e2e-9e4e-554b9c17c1a3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>ty-sub-price</value>
      <webElementGuid>cf268db7-b7e4-431a-ad7f-81cf614fd7ee</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>25,990,000</value>
      <webElementGuid>dca3b91f-66c8-4ce6-88be-655cb9f0fbdf</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;sec_product_price_2253224695&quot;)</value>
      <webElementGuid>0bda0cd7-c37c-4110-ba23-0b8d8a21130a</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//span[@id='sec_product_price_2253224695']</value>
      <webElementGuid>67bf33c8-bec6-4a35-a74d-7b98a94985a6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//td[@id='price_display_update_2253224695']/bdi/span</value>
      <webElementGuid>643676f9-8925-4bd9-af1b-a842ea9b2ec0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='đ'])[2]/preceding::span[1]</value>
      <webElementGuid>4889010d-9e56-4924-b2c5-054440709b48</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='đ'])[3]/preceding::span[3]</value>
      <webElementGuid>6e418081-220d-48f6-8af4-4609a98fb98c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//td[3]/bdi/span</value>
      <webElementGuid>38952b1f-e50a-4fa9-880c-2b009f6b555e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//span[@id = 'sec_product_price_2253224695' and (text() = '25,990,000' or . = '25,990,000')]</value>
      <webElementGuid>2971e0e1-8e52-4d8b-b153-625c42a01a3c</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
