<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>span_X-M5_B</name>
   <tag></tag>
   <elementGuidId>823f7f92-69cb-4862-9971-50e5dda13749</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#product_code_update_2253224695</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//span[@id='product_code_update_2253224695']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>62805efc-f4a5-41e7-8ade-6ed07ab31fee</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>cm-reload-2253224695</value>
      <webElementGuid>af36ee97-c275-424f-8022-664ba9e0a546</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>product_code_update_2253224695</value>
      <webElementGuid>1ac99214-7bb5-49d5-a6e3-ae085bc0b9bc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>X-M5_B</value>
      <webElementGuid>5c79f923-5401-4b36-b5a7-04c5994d0830</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;product_code_update_2253224695&quot;)</value>
      <webElementGuid>6d0f7c29-3a3b-437c-bbfc-8af943b6fdb1</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//span[@id='product_code_update_2253224695']</value>
      <webElementGuid>78faa71d-b910-4f0a-8f41-ee69e97527db</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='sku_2253224695']/span</value>
      <webElementGuid>3cd44dc6-b72b-4111-81d3-361cd3139a2b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='MÃ:'])[1]/following::span[1]</value>
      <webElementGuid>4c47b6d1-b6c3-441b-8c74-974389f2a1f9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Body Only • Black'])[1]/following::span[1]</value>
      <webElementGuid>11d59b87-710a-43f4-b7c2-46e3b3a74a24</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Tùy Chọn :'])[1]/preceding::span[1]</value>
      <webElementGuid>fdfaf1e8-d7eb-4856-9f9e-44a627be8e48</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Màu Sắc:'])[1]/preceding::span[1]</value>
      <webElementGuid>b75ac57b-891c-4f16-9ccc-496e75a04742</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='X-M5_B']/parent::*</value>
      <webElementGuid>e69048d7-0714-422e-ae5c-14580f51794e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//td[2]/div[2]/span</value>
      <webElementGuid>0acd53ef-2fd7-499b-83bf-7c74ed0858af</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//span[@id = 'product_code_update_2253224695' and (text() = 'X-M5_B' or . = 'X-M5_B')]</value>
      <webElementGuid>12c214c3-f9c0-491d-a5c0-cc5e50c17b71</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
