<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>strong_M</name>
   <tag></tag>
   <elementGuidId>add7e48f-b163-4fb9-beb3-0a4d78781fb4</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>strong</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='sku_2253224695']/strong</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>strong</value>
      <webElementGuid>6ab2b360-7854-4777-b34a-f9efe5f03d37</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>MÃ:</value>
      <webElementGuid>6968a231-d7ac-42a7-914b-d9ade2639163</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;sku_2253224695&quot;)/strong[1]</value>
      <webElementGuid>ad65e567-5f64-45ee-9f53-0fa3e785f919</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='sku_2253224695']/strong</value>
      <webElementGuid>37827173-b536-41ef-bfb2-8716c67193d7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Body Only • Black'])[1]/following::strong[1]</value>
      <webElementGuid>bd83a05b-7a3d-419e-9153-721c85ff9b2f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Fujifilm X-M5 (Chính hãng)'])[2]/following::strong[1]</value>
      <webElementGuid>cbd9b7c0-e4a1-4455-a2c6-61a6ba5f05c5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='X-M5_B'])[1]/preceding::strong[1]</value>
      <webElementGuid>bea35c7f-4363-4f7c-9fed-36bfd103bf03</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Tùy Chọn :'])[1]/preceding::strong[1]</value>
      <webElementGuid>1a9c5f81-cdcd-4486-bc9c-3b7bc6e6d519</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='MÃ:']/parent::*</value>
      <webElementGuid>19f3526a-2145-487f-b97a-0758d31e5aeb</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//strong</value>
      <webElementGuid>1d250cd7-b1bb-43ec-b730-3096a351ff53</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//strong[(text() = 'MÃ:' or . = 'MÃ:')]</value>
      <webElementGuid>d9a9918e-7d8e-432e-b363-942154338212</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
