<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>td_1</name>
   <tag></tag>
   <elementGuidId>da2aa150-0164-4a7d-a2da-b0ab852a7e9b</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>td:nth-of-type(3)</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='promotional_gift_2253224695']/table/tbody/tr/td[3]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>td</value>
      <webElementGuid>b03ea672-5e17-4a2b-ab08-939013043ca3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>
                                
                                1
                            </value>
      <webElementGuid>949c624b-770f-4bac-b44a-99eb4d786eb6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;promotional_gift_2253224695&quot;)/table[@class=&quot;ty-table&quot;]/tbody[1]/tr[1]/td[3]</value>
      <webElementGuid>234540ab-d6ee-4f69-8e70-1f76646db179</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='promotional_gift_2253224695']/table/tbody/tr/td[3]</value>
      <webElementGuid>ae53be09-813e-48ce-acc9-3a2e371bbe7b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Thẻ nhớ SDHC SanDisk Extreme Pro UHS-I 32GB 100MB/s'])[1]/following::td[2]</value>
      <webElementGuid>0ccd5786-904f-4b8e-8637-bce348bc9bdb</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Túi máy ảnh Baroca CA-702/s (Black)'])[1]/preceding::td[2]</value>
      <webElementGuid>1a4ebdd6-d0b9-4f00-8e9d-4bb6ecbe3836</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//bdi/div/div/table/tbody/tr/td[3]</value>
      <webElementGuid>0b347bbb-e848-4184-88c8-f9f67bcaad30</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//td[(text() = '
                                
                                1
                            ' or . = '
                                
                                1
                            ')]</value>
      <webElementGuid>4f873ec7-74be-48bb-bb2f-88d5ca9a1f5f</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
