<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>th_Sn phm</name>
   <tag></tag>
   <elementGuidId>7cab2325-9388-4fe4-8af7-9778638fd795</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#promotional_gift_2253224695 > table.ty-table > thead > tr > th</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='promotional_gift_2253224695']/table/thead/tr/th</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>th</value>
      <webElementGuid>62c4ea12-ee4f-46ac-8399-888daf8d8711</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Sản phẩm</value>
      <webElementGuid>3f99027f-5fab-4659-b097-e458a9727ffe</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;promotional_gift_2253224695&quot;)/table[@class=&quot;ty-table&quot;]/thead[1]/tr[1]/th[1]</value>
      <webElementGuid>a0ed4bd6-a5aa-429d-b9d9-d3cb29ae07d1</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='promotional_gift_2253224695']/table/thead/tr/th</value>
      <webElementGuid>526f00ae-ef6a-4aae-9bbb-f2ac243d2d3b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Quà tặng:'])[1]/following::th[1]</value>
      <webElementGuid>b1665953-18b7-4310-a775-a2ae9f1838fe</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Màu Sắc:'])[1]/following::th[1]</value>
      <webElementGuid>0e9d4250-b058-4114-8734-db909b87aac9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Số lượng'])[2]/preceding::th[1]</value>
      <webElementGuid>6871aabe-6608-4d8a-912b-294b949a65fb</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Thẻ nhớ SDHC SanDisk Extreme Pro UHS-I 32GB 100MB/s'])[1]/preceding::th[2]</value>
      <webElementGuid>1056acaa-8421-44ec-8107-d1ae5ee25248</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//bdi/div/div/table/thead/tr/th</value>
      <webElementGuid>d813969a-8d6a-447d-ae75-77972a30bc7e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//th[(text() = 'Sản phẩm' or . = 'Sản phẩm')]</value>
      <webElementGuid>5fc21908-5970-429c-9130-0268f1644944</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
