<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>label_Nh mt khu</name>
   <tag></tag>
   <elementGuidId>8bf2e52f-ddef-4ad8-96f8-ab5960ac435f</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='popup641_login_popup_form_container']/form/div[5]/div[2]/label</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>label.ty-login__remember-me-label</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>label</value>
      <webElementGuid>3b0079d7-fd7c-46fb-b02e-746df578b87b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>for</name>
      <type>Main</type>
      <value>remember_me_popup641</value>
      <webElementGuid>624f7663-8eda-412d-bd49-ddad3b945ec0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>ty-login__remember-me-label</value>
      <webElementGuid>691d6035-bdfc-496e-bfa6-84b3abd90a29</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Nhớ mật khẩu</value>
      <webElementGuid>addf42c3-30f8-498e-88d0-03b6b5ea2456</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;popup641_login_popup_form_container&quot;)/form[@class=&quot;cm-ajax cm-ajax-full-render cm-processed-form&quot;]/div[@class=&quot;buttons-container clearfix buttons-container-picker&quot;]/div[@class=&quot;ty-login__remember-me&quot;]/label[@class=&quot;ty-login__remember-me-label&quot;]</value>
      <webElementGuid>63369603-7d55-4b10-be40-646f6dad71c2</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='popup641_login_popup_form_container']/form/div[5]/div[2]/label</value>
      <webElementGuid>a59a84f7-861c-4174-b70a-09c4ed1512bc</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Đăng nhập'])[3]/following::label[1]</value>
      <webElementGuid>68d94da8-faea-4987-b163-7ce46c4f2e1c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Xác nhận chống bot'])[2]/following::label[1]</value>
      <webElementGuid>e6051a4d-d617-4b84-b394-5e59355ec0a4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Nhớ mật khẩu']/parent::*</value>
      <webElementGuid>fb927eef-e045-4011-b859-8ceac9f493bf</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[5]/div[2]/label</value>
      <webElementGuid>53198d88-16e9-4293-83d5-7d7ef6589e21</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//label[(text() = 'Nhớ mật khẩu' or . = 'Nhớ mật khẩu')]</value>
      <webElementGuid>7b2849e2-14df-48cc-a942-2f5b7e0eeb80</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
