<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>span_Trc</name>
   <tag></tag>
   <elementGuidId>be2b3003-680a-4dc8-8f90-a7ff576d688b</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>span.ty-pagination__text</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='pagination_blockY']/a/span</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>16b729de-bc9d-4a39-9124-6e580b476339</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>ty-pagination__text</value>
      <webElementGuid>29102949-5720-48f5-9d73-71e98256ba7a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Trước</value>
      <webElementGuid>8dd08070-a901-4e92-92ea-62595f58049d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;pagination_blockY&quot;)/a[@class=&quot;ty-pagination__item ty-pagination__btn ty-pagination__prev cm-history cm-ajax&quot;]/span[@class=&quot;ty-pagination__text&quot;]</value>
      <webElementGuid>92ba3a48-af94-4bd6-a2ec-6b0e8bae9587</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='pagination_blockY']/a/span</value>
      <webElementGuid>fa60fa41-b680-431f-a0c9-4e7311ffdfd7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Sony'])[22]/following::span[1]</value>
      <webElementGuid>16f8d357-1571-4f59-8a6d-b09441e5870e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Tiếp theo'])[1]/preceding::span[2]</value>
      <webElementGuid>98fec654-0f64-4e99-b807-a408322174f9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Trước']/parent::*</value>
      <webElementGuid>adc81c42-8815-49f2-b580-7a3d53bcc77f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div/a/span</value>
      <webElementGuid>cec35253-397f-4dc3-9711-05d1b0f8da1e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//span[(text() = 'Trước' or . = 'Trước')]</value>
      <webElementGuid>d148c79e-1293-4d59-a1db-96d11b33e14a</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
