<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button_Mua hng</name>
   <tag></tag>
   <elementGuidId>0a6aaf5a-50ab-43f9-910e-d5d6fce51143</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//button[@id='button_cart_66732']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#button_cart_66732</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>dee31656-7f23-44fe-b4a5-5e1502d205e7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>button_cart_66732</value>
      <webElementGuid>fd0162d4-63c7-42b2-b838-6646279bf39b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>ty-btn__primary ty-btn__add-to-cart cm-form-dialog-closer ty-btn</value>
      <webElementGuid>237f2279-291f-444f-bc93-543f93b3e825</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>submit</value>
      <webElementGuid>80e8b261-ca61-489c-abc4-ed01992c9b9f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>dispatch[checkout.add..66732]</value>
      <webElementGuid>9e8cc236-a0e7-4244-bd41-d7640b0c941e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Mua hàng</value>
      <webElementGuid>b68c4b5a-c7d0-40a0-a2ac-b5d6e0f70349</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;button_cart_66732&quot;)</value>
      <webElementGuid>61aac8e8-3373-40f6-98a1-a47e387227fe</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//button[@id='button_cart_66732']</value>
      <webElementGuid>95bd23d3-c678-40ad-9cc5-e62ae02b59bc</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='add_to_cart_update_66732']/button</value>
      <webElementGuid>48c75fec-6439-4384-8a4d-fd43c7ad01d0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Số lượng:'])[1]/following::button[1]</value>
      <webElementGuid>57b6acaa-df02-4422-ad7b-67741df79333</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Black'])[1]/following::button[1]</value>
      <webElementGuid>74fd8865-cd8f-40ff-a314-61772171e5a8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Mua nhanh'])[1]/preceding::button[1]</value>
      <webElementGuid>590d4f36-818f-4653-b8a7-439bd0621aa7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[6]/div/button</value>
      <webElementGuid>0980dd3a-b4b3-47fc-9a3d-76187b56f36f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//button[@id = 'button_cart_66732' and @type = 'submit' and @name = 'dispatch[checkout.add..66732]' and (text() = 'Mua hàng' or . = 'Mua hàng')]</value>
      <webElementGuid>d5496026-2b9d-488a-8f4e-5501d34390ce</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
