<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_E-mail_user_login</name>
   <tag></tag>
   <elementGuidId>85ea2c02-7f82-4ad5-b25e-2fa20adcdc10</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#login_popup641</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='login_popup641']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>a1a641f7-844f-4b14-a08b-ef2c23d14cdd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>5b3d4f33-6136-4a8c-883d-c97c6b4ce330</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>login_popup641</value>
      <webElementGuid>7efecdfc-5183-4843-b09c-91ebf27a81e7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>user_login</value>
      <webElementGuid>c75a259d-61dc-4671-9324-5447f7f05289</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>size</name>
      <type>Main</type>
      <value>30</value>
      <webElementGuid>cce87f95-539c-4bf7-a01a-59f3672c02df</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>ty-login__input cm-focus</value>
      <webElementGuid>476f1299-3018-4379-aee9-5c756bd08c32</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;login_popup641&quot;)</value>
      <webElementGuid>7f0e2928-b420-428f-ab91-3e33ca6eb2c7</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='login_popup641']</value>
      <webElementGuid>819f20c3-bf3b-4c59-ba43-3e9ef20b023e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='popup641_login_popup_form_container']/form/div/input</value>
      <webElementGuid>44acd275-683a-4a05-8bc2-162c546d1b6a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/form/div/input</value>
      <webElementGuid>44b0b71a-fa64-437c-833f-e566b2850f92</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @id = 'login_popup641' and @name = 'user_login']</value>
      <webElementGuid>bac80f25-99bf-42f7-9f66-db077e96f45e</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
