<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Qun mt khu_password</name>
   <tag></tag>
   <elementGuidId>7a0e6098-8c58-4bb8-addb-6fc39396cdf2</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#psw_popup641</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='psw_popup641']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>d72f1ecc-ea60-4696-bfce-0af52a848888</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>password</value>
      <webElementGuid>36ef60a1-0d03-4615-a3d9-9a6a8d7b1919</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>psw_popup641</value>
      <webElementGuid>f03da67f-506a-43b3-9570-87a93b2f2395</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>password</value>
      <webElementGuid>dc9d4b80-d913-4035-a244-555b0bb00a5c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>size</name>
      <type>Main</type>
      <value>30</value>
      <webElementGuid>dfbcd56b-b090-4fae-8e68-dece1d374048</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>ty-login__input</value>
      <webElementGuid>0e5c2bcc-4e1d-494a-8942-25d3eeba8f71</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>maxlength</name>
      <type>Main</type>
      <value>32</value>
      <webElementGuid>e6b4cf05-99a8-4204-b346-153f57490319</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;psw_popup641&quot;)</value>
      <webElementGuid>4ea7205f-5966-46da-b4fa-c9c249b84456</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='psw_popup641']</value>
      <webElementGuid>c76c9508-306d-43cf-8b1c-cd541dfca031</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='popup641_login_popup_form_container']/form/div[2]/input</value>
      <webElementGuid>930e2840-5ec2-49a0-b815-3c30cce684b8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/form/div[2]/input</value>
      <webElementGuid>0c2bb536-6c57-4bc5-a47f-ecee227129a4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'password' and @id = 'psw_popup641' and @name = 'password']</value>
      <webElementGuid>b813e52f-69b2-40c9-beb1-eb89b557f8b2</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
