<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>span_Mua hng</name>
   <tag></tag>
   <elementGuidId>ba35b62a-3b41-4cf1-99b3-0d6b36e37013</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#button_cart_66823 > span > span</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//button[@id='button_cart_66823']/span/span</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>2677be52-9ce5-4d84-b19d-b50aedafc3ed</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Mua hàng</value>
      <webElementGuid>ad50222e-53c1-44f4-bddc-7863a926aef1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;button_cart_66823&quot;)/span[1]/span[1]</value>
      <webElementGuid>728c0c84-4fbe-4af5-8d2a-c9a8ae8604a5</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//button[@id='button_cart_66823']/span/span</value>
      <webElementGuid>5946c74d-9afc-4b4e-8f96-2a616c0f9b26</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Số lượng:'])[1]/following::span[2]</value>
      <webElementGuid>1d128645-f032-4a38-87cf-f538c9295e51</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Mua nhanh'])[1]/preceding::span[1]</value>
      <webElementGuid>4d39e4c0-fa08-4b82-a398-d0f305c689f4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Mua ngay - trả sau'])[1]/preceding::span[2]</value>
      <webElementGuid>77ed86eb-b32e-4dbb-92f0-60550dd56f02</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Mua hàng']/parent::*</value>
      <webElementGuid>3b34bed9-8195-481e-b684-14b2413bce0d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[6]/div/button/span/span</value>
      <webElementGuid>3bdf7b7b-eacc-4560-86c3-aaf68027dc5e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//span[(text() = 'Mua hàng' or . = 'Mua hàng')]</value>
      <webElementGuid>e7312702-8206-46a1-b63e-4b0ae713dcdc</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
