<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_1</name>
   <tag></tag>
   <elementGuidId>a986b4ff-1eb2-4479-b577-03d3cffefd3c</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>div.ty-pagination__items > a.cm-history.ty-pagination__item.cm-ajax</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='pagination_blockY']/div/a</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>ffa78853-4927-41c0-9dfc-6f84af579f26</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-ca-scroll</name>
      <type>Main</type>
      <value>.cm-pagination-container</value>
      <webElementGuid>5cdaafaa-eb3f-4a0a-8c6b-07137f85c4cd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>https://zshop.vn/khuyen-mai/</value>
      <webElementGuid>7ad5656a-7fc6-4786-afc5-2cbc6ed874d8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-ca-page</name>
      <type>Main</type>
      <value>1</value>
      <webElementGuid>2a6207cf-a8fa-4254-bbc4-6142c05172c4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>cm-history ty-pagination__item cm-ajax</value>
      <webElementGuid>0be22735-9c4d-43fc-a482-a622526e7b67</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-ca-target-id</name>
      <type>Main</type>
      <value>pagination_contents</value>
      <webElementGuid>8121e6fb-8915-47fb-ae13-08f269f1bad5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>1</value>
      <webElementGuid>1bd2ed68-596c-4f70-ae1c-f9294a163664</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;pagination_blockY&quot;)/div[@class=&quot;ty-pagination__items&quot;]/a[@class=&quot;cm-history ty-pagination__item cm-ajax&quot;]</value>
      <webElementGuid>e8b01f34-4f13-4b97-9172-0bf228a86ef1</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='pagination_blockY']/div/a</value>
      <webElementGuid>2dddd4c6-8cd6-4ac8-8598-afd7936b86ca</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>(//a[contains(text(),'1')])[68]</value>
      <webElementGuid>30329fc3-9815-4624-9def-1153a9462bb3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Trước'])[1]/following::a[1]</value>
      <webElementGuid>e35bf493-c9e9-40af-b945-037d5ec60edd</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Tiếp theo'])[1]/preceding::a[8]</value>
      <webElementGuid>a8c94e25-bb6c-4bed-9922-7279b6ffcb13</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='1']/parent::*</value>
      <webElementGuid>64d13a85-f68e-4372-909d-1945b7efa8df</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>(//a[contains(@href, 'https://zshop.vn/khuyen-mai/')])[14]</value>
      <webElementGuid>f0439c5f-0fd3-460d-9879-46188b7444a0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[4]/div/div/a</value>
      <webElementGuid>c2052217-3b80-487d-9c7a-971d176ba8ad</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = 'https://zshop.vn/khuyen-mai/' and (text() = '1' or . = '1')]</value>
      <webElementGuid>ced81cde-316d-40b1-9586-1281e74bb513</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
