<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_2</name>
   <tag></tag>
   <elementGuidId>c1b5a061-f223-4584-bc08-9eef874139fd</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>div.ty-pagination__items > a.cm-history.ty-pagination__item.cm-ajax</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='pagination_blockY']/div/a</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>5bd4af8e-a882-4eaf-95c5-ea0266cf37fb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-ca-scroll</name>
      <type>Main</type>
      <value>.cm-pagination-container</value>
      <webElementGuid>6f10afda-cf48-48b2-bf38-3c6a19cdb914</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>https://zshop.vn/khuyen-mai/page-2/</value>
      <webElementGuid>34d5d127-0d3a-41a3-aeaf-edc7fdff6002</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-ca-page</name>
      <type>Main</type>
      <value>2</value>
      <webElementGuid>b24d24be-a11f-482a-be07-7f0a047a3a1a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>cm-history ty-pagination__item cm-ajax</value>
      <webElementGuid>344ae31b-14ea-4490-86ba-108a8fc6b903</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-ca-target-id</name>
      <type>Main</type>
      <value>pagination_contents</value>
      <webElementGuid>706c6b0b-a80f-4a79-8eab-9ab8a6f9b11d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>2</value>
      <webElementGuid>b677ecb6-95e4-4379-9476-106cb6e80de9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;pagination_blockY&quot;)/div[@class=&quot;ty-pagination__items&quot;]/a[@class=&quot;cm-history ty-pagination__item cm-ajax&quot;]</value>
      <webElementGuid>3ed3c99b-01cb-4eb6-af90-c0d7a88335f0</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='pagination_blockY']/div/a</value>
      <webElementGuid>26044f12-9fea-4810-ab04-74e8b6e4c7fb</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>(//a[contains(text(),'2')])[55]</value>
      <webElementGuid>0d2f3b51-35b0-4227-943c-c8ea25a6dd44</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Trước'])[1]/following::a[1]</value>
      <webElementGuid>03f32bd6-7232-4d4c-beca-9e1c8dcff943</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Tiếp theo'])[1]/preceding::a[7]</value>
      <webElementGuid>74aca2eb-1fa8-469f-928c-bc83bcf34871</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='2']/parent::*</value>
      <webElementGuid>5adab2a4-4024-40ac-be9d-30fed2dd1294</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>(//a[contains(@href, 'https://zshop.vn/khuyen-mai/page-2/')])[2]</value>
      <webElementGuid>21df2e03-3633-4742-a117-148a0fdf8743</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[4]/div/div/a</value>
      <webElementGuid>a0f0f786-b5ee-4023-bfa6-9f344f33fddf</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = 'https://zshop.vn/khuyen-mai/page-2/' and (text() = '2' or . = '2')]</value>
      <webElementGuid>92f13a87-01ca-4275-a943-d9c63ca4715a</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
