<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>big_</name>
   <tag></tag>
   <elementGuidId>f5d8f25e-4737-404c-8fd2-a331d7992ae2</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>big</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>(.//*[normalize-space(text()) and normalize-space(.)='ESC'])[1]/preceding::big[1]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>big</value>
      <webElementGuid>b98c1528-3607-418e-8fb9-63ca32674753</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>×</value>
      <webElementGuid>3fe26c39-dec4-4278-8435-141c39bbee9a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/html[@class=&quot;cookies filereader draganddrop no-touchevents mouseevents&quot;]/body[@class=&quot;screen--md&quot;]/div[@class=&quot;sp-backdrop-info show-prompt&quot;]/div[@class=&quot;backdrop-close&quot;]/big[1]</value>
      <webElementGuid>ba4d33b3-786d-4c4d-9144-762e01668d82</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='ESC'])[1]/preceding::big[1]</value>
      <webElementGuid>046a62fe-9a9c-42ad-a75b-da65fa7cf90e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Hiển thị chương trình ưu đãi mới nhất!'])[1]/preceding::big[1]</value>
      <webElementGuid>ac4b4466-51b5-4474-9f27-0152bf99cdfc</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='×']/parent::*</value>
      <webElementGuid>23bb387b-22e7-4302-94f9-bcfa61811420</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//big</value>
      <webElementGuid>d5474dfb-dd49-4ebf-8a31-e0ad985b2a50</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//big[(text() = '×' or . = '×')]</value>
      <webElementGuid>52e5f9f2-28a2-4635-824c-2e017a4790c2</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
