<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_E-mail_user_login</name>
   <tag></tag>
   <elementGuidId>1af1cf27-0ca3-41ea-9978-2da882b8954c</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#login_popup641</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='login_popup641']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>ffa41d0e-0aba-4307-b933-d3990540f768</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>792be6f0-71f9-4588-b8c3-3a86542f9fc8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>login_popup641</value>
      <webElementGuid>0258f0f2-779e-49b5-9b6b-1491b58e42ba</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>user_login</value>
      <webElementGuid>6330d50f-9e51-4c07-9f8a-4ecc7d6521bc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>size</name>
      <type>Main</type>
      <value>30</value>
      <webElementGuid>31ee6ad7-d847-4522-9505-38ce6a381696</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>ty-login__input cm-focus</value>
      <webElementGuid>81d5771e-d3df-49da-9913-6a1d58022de6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;login_popup641&quot;)</value>
      <webElementGuid>eab33cb1-f6a8-4607-b114-f3d5286bbe13</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='login_popup641']</value>
      <webElementGuid>d705f2f8-b834-4848-9084-9e060fac7fc5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='popup641_login_popup_form_container']/form/div/input</value>
      <webElementGuid>27995a88-645c-4352-8198-1b7e9c422f36</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/form/div/input</value>
      <webElementGuid>a7818734-e402-4995-b7ee-25cb8040d97d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @id = 'login_popup641' and @name = 'user_login']</value>
      <webElementGuid>400c2794-cb18-4443-b688-25915a4a3b64</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
