<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Qun mt khu_password</name>
   <tag></tag>
   <elementGuidId>8ec87c16-3022-4e2a-bb61-7daada1f5ce6</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#psw_popup641</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='psw_popup641']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>8a9b9e29-ae1b-4ad3-be04-979cfacccdcb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>password</value>
      <webElementGuid>14cc969b-43d8-495a-ae60-90c97b1201e5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>psw_popup641</value>
      <webElementGuid>88935dca-a26a-40c3-8f2f-58ad3ca7826a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>password</value>
      <webElementGuid>e731ed90-3a9a-4018-9cd7-0c1fe9684e8b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>size</name>
      <type>Main</type>
      <value>30</value>
      <webElementGuid>f5d81ec2-3b09-4c71-a2b6-3fc1aced5921</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>ty-login__input</value>
      <webElementGuid>51126e41-a7cf-4853-a387-218d42df23de</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>maxlength</name>
      <type>Main</type>
      <value>32</value>
      <webElementGuid>4aa34877-cd1a-43f0-b282-8ecbecb565a9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;psw_popup641&quot;)</value>
      <webElementGuid>fd597b85-d5cd-40e8-8418-2a5901d27d97</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='psw_popup641']</value>
      <webElementGuid>9d71523d-988e-4c0d-9011-5d6e9faadc6b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='popup641_login_popup_form_container']/form/div[2]/input</value>
      <webElementGuid>79f80222-a499-44be-bff2-98e8d72884bd</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/form/div[2]/input</value>
      <webElementGuid>abab124b-c647-49a4-a7a6-7ffe70f59886</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'password' and @id = 'psw_popup641' and @name = 'password']</value>
      <webElementGuid>4d1b3186-f089-4edf-a06f-da40ffd01821</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
