<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Nh mt khu_q</name>
   <tag></tag>
   <elementGuidId>59a2b889-1722-4a94-a669-f084dba0baa0</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#search_input</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='search_input']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>572550f2-9613-45b0-a1ae-26041524c23a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>81fe6310-9833-4861-bd03-02f8ede9a389</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>q</value>
      <webElementGuid>87598e06-ebda-40e5-a812-ad4c8d2d70d6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>search_input</value>
      <webElementGuid>0b44bb4e-0ce8-4ec8-a58b-c754197d87ee</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>title</name>
      <type>Main</type>
      <value>Tìm kiếm sản phẩm</value>
      <webElementGuid>8b67d242-b8af-4cbe-92ea-a1b7528094f8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>ty-search-block__input cm-hint-focused</value>
      <webElementGuid>1303d265-ed7c-422d-94cb-d840bff6cc5b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;search_input&quot;)</value>
      <webElementGuid>6f2ebcaf-5daa-4fb5-866c-cf0a935a9189</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='search_input']</value>
      <webElementGuid>d33335ae-a873-4aec-bdd0-0c151ba27bcd</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='tygh_main_container']/div/div/div[2]/div/div[2]/div[4]/div/form/input[9]</value>
      <webElementGuid>e78f4d9b-4cd3-43d9-927c-49ed77664237</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//input[9]</value>
      <webElementGuid>9fb8aa31-10b2-44b1-8aa7-6a6976cc7d98</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @name = 'q' and @id = 'search_input' and @title = 'Tìm kiếm sản phẩm']</value>
      <webElementGuid>d6cd57f5-5146-4856-b83f-84e1334298f9</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
