<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>p_Khng tm thy sn phm ph hp vi tiu ch tm kim</name>
   <tag></tag>
   <elementGuidId>5724777d-9e31-4d75-a1f2-dcc330cbd627</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>p.ty-no-items</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='products_search_11']/p</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>p</value>
      <webElementGuid>38e89a58-2e4e-4b48-9d79-7c1b235d31fc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>ty-no-items</value>
      <webElementGuid>509fdec7-0e60-4641-a746-f55f3e45b867</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Không tìm thấy sản phẩm phù hợp với tiêu chí tìm kiếm</value>
      <webElementGuid>391ade10-90fd-4f5c-933d-5c17c552c0df</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;products_search_11&quot;)/p[@class=&quot;ty-no-items&quot;]</value>
      <webElementGuid>96a74306-1acf-42c3-aee5-f44c4b1b50e7</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='products_search_11']/p</value>
      <webElementGuid>e100a51b-e59b-41a9-9e95-18dfa1b63c68</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Kết quả tìm kiếm'])[2]/following::p[1]</value>
      <webElementGuid>68232bdc-2bc0-4826-b5dc-52591a6de176</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='iPad Pro | Pro 9.7 cũ'])[1]/following::p[1]</value>
      <webElementGuid>fb1bdd91-3071-4e0c-9f9f-bb4087d90182</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Nhận bản tin của zShop'])[1]/preceding::p[1]</value>
      <webElementGuid>a1d82e8e-07c9-475d-9ffe-6a94c1941f8e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Không tìm thấy sản phẩm phù hợp với tiêu chí tìm kiếm']/parent::*</value>
      <webElementGuid>cf14c22c-b7c5-476f-b865-b5ea3199de54</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//p</value>
      <webElementGuid>38a9c22d-cdf8-4a03-95aa-fcfafd849770</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//p[(text() = 'Không tìm thấy sản phẩm phù hợp với tiêu chí tìm kiếm' or . = 'Không tìm thấy sản phẩm phù hợp với tiêu chí tìm kiếm')]</value>
      <webElementGuid>d5b0690a-bb04-447d-8099-bfb7d527e01e</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
