<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>bdi_Khuyn Mi</name>
   <tag></tag>
   <elementGuidId>75c3a701-502c-4b4e-8b1d-7965cb331766</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>bdi</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='tygh_main_container']/div[2]/div/div/div/div/div/div/div/ul/li[2]/a[2]/span/bdi</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>bdi</value>
      <webElementGuid>131bef2b-a0c9-4ff5-886e-73b5a33efc79</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Khuyến Mãi</value>
      <webElementGuid>e4bce217-6bf5-4c5c-b6c5-57521eba3d38</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;tygh_main_container&quot;)/div[@class=&quot;tygh-header clearfix&quot;]/div[@class=&quot;container-fluid  header-grid&quot;]/div[@class=&quot;container-fluid-row container-fluid-row-full-width top-menu-grid&quot;]/div[@class=&quot;row-fluid&quot;]/div[@class=&quot;span16&quot;]/div[@class=&quot;top-menu&quot;]/div[@class=&quot;abt_up-menu extended&quot;]/div[@class=&quot;ty-menu__wrapper&quot;]/ul[@class=&quot;ty-menu__items cm-responsive-menu abt_inited&quot;]/li[@class=&quot;ty-menu__item cm-menu-item-responsive&quot;]/a[@class=&quot;ty-menu__item-link a-first-lvl&quot;]/span[@class=&quot;item-with-icon&quot;]/bdi[1]</value>
      <webElementGuid>9ac05f4f-dcbf-4fb3-b405-fc63602cd1fe</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='tygh_main_container']/div[2]/div/div/div/div/div/div/div/ul/li[2]/a[2]/span/bdi</value>
      <webElementGuid>e153c302-72b7-4543-a0ee-0ad7e288020e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)=''])[1]/following::bdi[1]</value>
      <webElementGuid>82a8d87b-07d4-4490-a4d8-7d8488db2565</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)=''])[1]/following::bdi[1]</value>
      <webElementGuid>bbf320e6-b17d-4395-be4f-77deb42716e9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Khuyến mãi Máy ảnh'])[1]/preceding::bdi[1]</value>
      <webElementGuid>9caf9509-ae01-46b3-a5a0-6d30dffb8581</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Khuyến Mãi']/parent::*</value>
      <webElementGuid>82733b3b-aaff-43c0-b214-a9af1f2908c8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//bdi</value>
      <webElementGuid>4fbe303b-eac3-42e5-8168-8435a9d0b4ef</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//bdi[(text() = 'Khuyến Mãi' or . = 'Khuyến Mãi')]</value>
      <webElementGuid>ea323802-2958-4c15-8d0e-adb76ed0d5cc</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
