<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_Mc mi nht u tin                        _333234</name>
   <tag></tag>
   <elementGuidId>6f664138-21a9-41d8-9d11-86761050d595</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#category_products_11</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='category_products_11']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>aabdd4e6-3b01-4c3a-800b-b6809ed92b4d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>cat-view-grid</value>
      <webElementGuid>caf8be3d-fbaa-4042-accc-cff7348fd799</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>category_products_11</value>
      <webElementGuid>7e516286-6fdd-4460-bdef-fb378cd8a97a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>

        
                
            

    
    

    

    
    

    

    

    

    

    
    
	    Mục mới nhất đầu tiên
                                                                                                
                                                                                                                                                                                                                                                                                        
                                                                                                                                                                                                                                                
                                                                                                                                                                                                                                                                                                                            
                                                                                                            
                        Xếp theo Tên: A đến Z
                    
                                                                                                                                                
                        Xếp theo Tên: Z đến A
                    
                                                                                                                                                
                                                                                                            
                        Xếp theo giá: Thấp đến Cao
                    
                                                                                                                                                
                        Xếp theo giá: Cao đến Thấp
                    
                                                                                                                                                
                                                                                                                                                                                                                                                                                                                            
                                                                                                                                                                                                                                                                                                                            
                                                                                                                                                                                                                                        







    
	    	40 Mỗi trang
                            
                16 Mỗi trang
            
                                    
                32 Mỗi trang
            
                                                    
                64 Mỗi trang
            
                                    
                128 Mỗi trang
            
                    










































    
                
        
                                                        
                                                    
                                            
                                        




    
                    
                    
                            


    
                            
        
        


    

            
                    
                                            





                    
                
                    
                                            





                    
                
                    
                                            





                    
                
                    
                                            





                    
                
                    
                                            





                    
                
                    
                                            





                    
                
                                            
                                                
                                                
                                                
                                                
                                                
                        

                                        		                    
                            
                        
                            

				                	                	                                
                    
    
        Giảm 9%
    

                        
	        
    
        Giảm Thêm 9%
    


        
                
            
    ThinkPad T14 Gen 4 - Core i5-1345U / 16GB / 256GB / 14&quot; WUXGA

                
        
        
                            
                    
                
                        
            
            
            	        	                	21,990,000 đ
	            	                    

        
        
        
        
        
                                
                                    19,990,000 đ
                            

                    
	    
	        

            
        


                                    
                                        
            
            
                        
            

        Kích cỡ màn hình14 inch    ModelLenovo ThinkPad T14    OptionThinkPad T14 Gen 4
        
    


                
                                                                        
                    
                                        






































    
                
        
                                                        
                                                    
                                            
                                        




    
                    
                    
                            


    
                            
        
        


    

            
                    
                                            





                    
                
                    
                                            





                    
                
                    
                                            





                    
                
                    
                                            





                    
                
                    
                                            





                    
                
                    
                                            





                    
                
                                            
                                                
                                                
                                                
                                                
                                                
                        

                                        		                    
                            
                        
                            

				                	                	                                
                    
    
        Giảm 14%
    

                        
	        
    
        Giảm Thêm 14%
    


        
                
            
    ThinkPad T14 Gen 4 - Intel Core i5-1335U / 32GB / 512GB SSD / 14&quot; 2.2K / Bảo hành 3 năm

                
        
        
                            
                    
                
                        
            
            
            	        	                	34,990,000 đ
	            	                    

        
        
        
        
        
                                
                                    29,990,000 đ
                            

                    
	    
	        

            
        


                                    
                                        
            
            
                        
            

        Kích cỡ màn hình14 inch    ModelLenovo ThinkPad T14    OptionThinkPad T14 Gen 4
        
    


                
                                                                        
                    
                                        






































    
                
        
                                                        
                                                    
                                            
                                        




    
                    
                    
                            


    
                            
        
        


    

            
                    
                                            





                    
                
                    
                                            





                    
                
                    
                                            





                    
                
                    
                                            





                    
                
                    
                                            





                    
                
                    
                                            





                    
                
                                            
                                                
                                                
                                                
                                                
                                                
                        

                                        		                    
                            
                        
                            

				                	                	                                
                    
    
        Giảm 15%
    

                        
	        
    
        Giảm Thêm 15%
    


        
                
            
    ThinkPad T14 Gen 4 - Intel Core i5-1335U / 16GB / 512GB SSD / 14&quot; 2.2K / Bảo hành 3 năm

                
        
        
                            
                    
                
                        
            
            
            	        	                	32,990,000 đ
	            	                    

        
        
        
        
        
                                
                                    27,990,000 đ
                            

                    
	    
	        

            
        


                                    
                                        
            
            
                        
            

        Kích cỡ màn hình14 inch    ModelLenovo ThinkPad T14    OptionThinkPad T14 Gen 4
        
    


                
                                                                        
                    
                                        






































    
                
        
                                                        
                                                    
                                            
                                        




    
                    
                    
                            


    
                            
        
        


    

            
                    
                                            





                    
                
                    
                                            





                    
                
                    
                                            





                    
                
                    
                                            





                    
                
                    
                                            





                    
                
                    
                                            





                    
                
                                            
                                                
                                                
                                                
                                                
                                                
                        

                                        		                    
                            
                        
                            

				                	                	                                
                    
    
        Giảm 17%
    

                        
	        
    
        Giảm Thêm 17%
    


        
                
            
    ThinkPad T14 Gen 4 - Intel Core i5-1340P / 16GB / 512GB / 14&quot; WUXGA

                 
                        
            
            
            	        	                	29,990,000 đ
	            	                    

        
        
        
        
        
                                
                                    24,990,000 đ
                            

                    
	    
	        

            
        
                
                                                        
                                
                    
                        Bảo Hành:
                    

                    						                            
                            
                                
                                                                    
                                   Bảo hành 1 năm
                                
                                                            


                            						                                                        
                                

                        
        
    

                                    
                                        
            
            
                        
            

        Kích cỡ màn hình14 inch    ModelLenovo ThinkPad T14    OptionThinkPad T14 Gen 4
        
    


                
                                                                        
                    
                                        






































    
                
        
                                                        
                        	                        
	                                Tạm hết hàng
	                        
                                            
                                        




    
                    
                    
                            


    
                            
        
        


    

            
                    
                                            





                    
                
                    
                                            





                    
                
                    
                                            





                    
                
                    
                                            





                    
                
                    
                                            





                    
                
                    
                                            





                    
                
                    
                                            





                    
                
                    
                                            





                    
                
                    
                                            





                    
                
                    
                                            





                    
                
                    
                                            





                    
                
                    
                                            





                    
                
                                            
                                                
                                                
                                                
                                                
                                                
                                                
                                                
                                                
                                                
                                                
                                                
                        

                                        		                    
                            
                        
                            

				                	                	                                
                    
    
        Giảm 12%
    

                        
	        
    
        Giảm Thêm 12%
    


        
                
            
    ThinkPad X1 Carbon Gen 11 - Intel Core i5-1335U / 16GB / 256GB SSD / 14&quot; WUXGA

                
        
        
                            
                    
                
                        
            
            
            	        	                	32,500,000 đ
	            	                    

        
        
        
        
        
                                
                                    28,500,000 đ
                            

                    
	    
	        

            
        


                                    
                                        
            
            
                        
            

        Kích cỡ màn hình14 inch    ModelLenovo ThinkPad X1 Carbon    OptionThinkPad X1 Carbon Gen 11
        
    


                
                                                                        
                    
                                        


	    
        
        	    
		
	


    
    
        

        
            


    
    
    


        
    

</value>
      <webElementGuid>72c3835b-c6ce-4fba-83c8-5f933979ac87</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;category_products_11&quot;)</value>
      <webElementGuid>391be48d-b11e-40ab-a65f-4610816e0d92</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//div[@id='category_products_11']</value>
      <webElementGuid>5c3d0f23-732b-48de-9850-4900b496c061</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='tygh_main_container']/div[3]/div/div/div/div[2]/div[7]</value>
      <webElementGuid>00d75cbe-b866-41b4-9b78-48a397610c52</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)=''])[1]/following::div[1]</value>
      <webElementGuid>e778c560-87ff-48f8-8cf8-4ecdebf1eb11</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Xem thêm'])[1]/following::div[3]</value>
      <webElementGuid>7301fdd1-b609-42d7-98e8-0ca3c2f5a498</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div[7]</value>
      <webElementGuid>db25b5be-ff32-439a-a5a4-150fa1181567</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[@id = 'category_products_11' and (text() = '

        
                
            

    
    

    

    
    

    

    

    

    

    
    
	    Mục mới nhất đầu tiên
                                                                                                
                                                                                                                                                                                                                                                                                        
                                                                                                                                                                                                                                                
                                                                                                                                                                                                                                                                                                                            
                                                                                                            
                        Xếp theo Tên: A đến Z
                    
                                                                                                                                                
                        Xếp theo Tên: Z đến A
                    
                                                                                                                                                
                                                                                                            
                        Xếp theo giá: Thấp đến Cao
                    
                                                                                                                                                
                        Xếp theo giá: Cao đến Thấp
                    
                                                                                                                                                
                                                                                                                                                                                                                                                                                                                            
                                                                                                                                                                                                                                                                                                                            
                                                                                                                                                                                                                                        







    
	    	40 Mỗi trang
                            
                16 Mỗi trang
            
                                    
                32 Mỗi trang
            
                                                    
                64 Mỗi trang
            
                                    
                128 Mỗi trang
            
                    










































    
                
        
                                                        
                                                    
                                            
                                        




    
                    
                    
                            


    
                            
        
        


    

            
                    
                                            





                    
                
                    
                                            





                    
                
                    
                                            





                    
                
                    
                                            





                    
                
                    
                                            





                    
                
                    
                                            





                    
                
                                            
                                                
                                                
                                                
                                                
                                                
                        

                                        		                    
                            
                        
                            

				                	                	                                
                    
    
        Giảm 9%
    

                        
	        
    
        Giảm Thêm 9%
    


        
                
            
    ThinkPad T14 Gen 4 - Core i5-1345U / 16GB / 256GB / 14&quot; WUXGA

                
        
        
                            
                    
                
                        
            
            
            	        	                	21,990,000 đ
	            	                    

        
        
        
        
        
                                
                                    19,990,000 đ
                            

                    
	    
	        

            
        


                                    
                                        
            
            
                        
            

        Kích cỡ màn hình14 inch    ModelLenovo ThinkPad T14    OptionThinkPad T14 Gen 4
        
    


                
                                                                        
                    
                                        






































    
                
        
                                                        
                                                    
                                            
                                        




    
                    
                    
                            


    
                            
        
        


    

            
                    
                                            





                    
                
                    
                                            





                    
                
                    
                                            





                    
                
                    
                                            





                    
                
                    
                                            





                    
                
                    
                                            





                    
                
                                            
                                                
                                                
                                                
                                                
                                                
                        

                                        		                    
                            
                        
                            

				                	                	                                
                    
    
        Giảm 14%
    

                        
	        
    
        Giảm Thêm 14%
    


        
                
            
    ThinkPad T14 Gen 4 - Intel Core i5-1335U / 32GB / 512GB SSD / 14&quot; 2.2K / Bảo hành 3 năm

                
        
        
                            
                    
                
                        
            
            
            	        	                	34,990,000 đ
	            	                    

        
        
        
        
        
                                
                                    29,990,000 đ
                            

                    
	    
	        

            
        


                                    
                                        
            
            
                        
            

        Kích cỡ màn hình14 inch    ModelLenovo ThinkPad T14    OptionThinkPad T14 Gen 4
        
    


                
                                                                        
                    
                                        






































    
                
        
                                                        
                                                    
                                            
                                        




    
                    
                    
                            


    
                            
        
        


    

            
                    
                                            





                    
                
                    
                                            





                    
                
                    
                                            





                    
                
                    
                                            





                    
                
                    
                                            





                    
                
                    
                                            





                    
                
                                            
                                                
                                                
                                                
                                                
                                                
                        

                                        		                    
                            
                        
                            

				                	                	                                
                    
    
        Giảm 15%
    

                        
	        
    
        Giảm Thêm 15%
    


        
                
            
    ThinkPad T14 Gen 4 - Intel Core i5-1335U / 16GB / 512GB SSD / 14&quot; 2.2K / Bảo hành 3 năm

                
        
        
                            
                    
                
                        
            
            
            	        	                	32,990,000 đ
	            	                    

        
        
        
        
        
                                
                                    27,990,000 đ
                            

                    
	    
	        

            
        


                                    
                                        
            
            
                        
            

        Kích cỡ màn hình14 inch    ModelLenovo ThinkPad T14    OptionThinkPad T14 Gen 4
        
    


                
                                                                        
                    
                                        






































    
                
        
                                                        
                                                    
                                            
                                        




    
                    
                    
                            


    
                            
        
        


    

            
                    
                                            





                    
                
                    
                                            





                    
                
                    
                                            





                    
                
                    
                                            





                    
                
                    
                                            





                    
                
                    
                                            





                    
                
                                            
                                                
                                                
                                                
                                                
                                                
                        

                                        		                    
                            
                        
                            

				                	                	                                
                    
    
        Giảm 17%
    

                        
	        
    
        Giảm Thêm 17%
    


        
                
            
    ThinkPad T14 Gen 4 - Intel Core i5-1340P / 16GB / 512GB / 14&quot; WUXGA

                 
                        
            
            
            	        	                	29,990,000 đ
	            	                    

        
        
        
        
        
                                
                                    24,990,000 đ
                            

                    
	    
	        

            
        
                
                                                        
                                
                    
                        Bảo Hành:
                    

                    						                            
                            
                                
                                                                    
                                   Bảo hành 1 năm
                                
                                                            


                            						                                                        
                                

                        
        
    

                                    
                                        
            
            
                        
            

        Kích cỡ màn hình14 inch    ModelLenovo ThinkPad T14    OptionThinkPad T14 Gen 4
        
    


                
                                                                        
                    
                                        






































    
                
        
                                                        
                        	                        
	                                Tạm hết hàng
	                        
                                            
                                        




    
                    
                    
                            


    
                            
        
        


    

            
                    
                                            





                    
                
                    
                                            





                    
                
                    
                                            





                    
                
                    
                                            





                    
                
                    
                                            





                    
                
                    
                                            





                    
                
                    
                                            





                    
                
                    
                                            





                    
                
                    
                                            





                    
                
                    
                                            





                    
                
                    
                                            





                    
                
                    
                                            





                    
                
                                            
                                                
                                                
                                                
                                                
                                                
                                                
                                                
                                                
                                                
                                                
                                                
                        

                                        		                    
                            
                        
                            

				                	                	                                
                    
    
        Giảm 12%
    

                        
	        
    
        Giảm Thêm 12%
    


        
                
            
    ThinkPad X1 Carbon Gen 11 - Intel Core i5-1335U / 16GB / 256GB SSD / 14&quot; WUXGA

                
        
        
                            
                    
                
                        
            
            
            	        	                	32,500,000 đ
	            	                    

        
        
        
        
        
                                
                                    28,500,000 đ
                            

                    
	    
	        

            
        


                                    
                                        
            
            
                        
            

        Kích cỡ màn hình14 inch    ModelLenovo ThinkPad X1 Carbon    OptionThinkPad X1 Carbon Gen 11
        
    


                
                                                                        
                    
                                        


	    
        
        	    
		
	


    
    
        

        
            


    
    
    


        
    

' or . = '

        
                
            

    
    

    

    
    

    

    

    

    

    
    
	    Mục mới nhất đầu tiên
                                                                                                
                                                                                                                                                                                                                                                                                        
                                                                                                                                                                                                                                                
                                                                                                                                                                                                                                                                                                                            
                                                                                                            
                        Xếp theo Tên: A đến Z
                    
                                                                                                                                                
                        Xếp theo Tên: Z đến A
                    
                                                                                                                                                
                                                                                                            
                        Xếp theo giá: Thấp đến Cao
                    
                                                                                                                                                
                        Xếp theo giá: Cao đến Thấp
                    
                                                                                                                                                
                                                                                                                                                                                                                                                                                                                            
                                                                                                                                                                                                                                                                                                                            
                                                                                                                                                                                                                                        







    
	    	40 Mỗi trang
                            
                16 Mỗi trang
            
                                    
                32 Mỗi trang
            
                                                    
                64 Mỗi trang
            
                                    
                128 Mỗi trang
            
                    










































    
                
        
                                                        
                                                    
                                            
                                        




    
                    
                    
                            


    
                            
        
        


    

            
                    
                                            





                    
                
                    
                                            





                    
                
                    
                                            





                    
                
                    
                                            





                    
                
                    
                                            





                    
                
                    
                                            





                    
                
                                            
                                                
                                                
                                                
                                                
                                                
                        

                                        		                    
                            
                        
                            

				                	                	                                
                    
    
        Giảm 9%
    

                        
	        
    
        Giảm Thêm 9%
    


        
                
            
    ThinkPad T14 Gen 4 - Core i5-1345U / 16GB / 256GB / 14&quot; WUXGA

                
        
        
                            
                    
                
                        
            
            
            	        	                	21,990,000 đ
	            	                    

        
        
        
        
        
                                
                                    19,990,000 đ
                            

                    
	    
	        

            
        


                                    
                                        
            
            
                        
            

        Kích cỡ màn hình14 inch    ModelLenovo ThinkPad T14    OptionThinkPad T14 Gen 4
        
    


                
                                                                        
                    
                                        






































    
                
        
                                                        
                                                    
                                            
                                        




    
                    
                    
                            


    
                            
        
        


    

            
                    
                                            





                    
                
                    
                                            





                    
                
                    
                                            





                    
                
                    
                                            





                    
                
                    
                                            





                    
                
                    
                                            





                    
                
                                            
                                                
                                                
                                                
                                                
                                                
                        

                                        		                    
                            
                        
                            

				                	                	                                
                    
    
        Giảm 14%
    

                        
	        
    
        Giảm Thêm 14%
    


        
                
            
    ThinkPad T14 Gen 4 - Intel Core i5-1335U / 32GB / 512GB SSD / 14&quot; 2.2K / Bảo hành 3 năm

                
        
        
                            
                    
                
                        
            
            
            	        	                	34,990,000 đ
	            	                    

        
        
        
        
        
                                
                                    29,990,000 đ
                            

                    
	    
	        

            
        


                                    
                                        
            
            
                        
            

        Kích cỡ màn hình14 inch    ModelLenovo ThinkPad T14    OptionThinkPad T14 Gen 4
        
    


                
                                                                        
                    
                                        






































    
                
        
                                                        
                                                    
                                            
                                        




    
                    
                    
                            


    
                            
        
        


    

            
                    
                                            





                    
                
                    
                                            





                    
                
                    
                                            





                    
                
                    
                                            





                    
                
                    
                                            





                    
                
                    
                                            





                    
                
                                            
                                                
                                                
                                                
                                                
                                                
                        

                                        		                    
                            
                        
                            

				                	                	                                
                    
    
        Giảm 15%
    

                        
	        
    
        Giảm Thêm 15%
    


        
                
            
    ThinkPad T14 Gen 4 - Intel Core i5-1335U / 16GB / 512GB SSD / 14&quot; 2.2K / Bảo hành 3 năm

                
        
        
                            
                    
                
                        
            
            
            	        	                	32,990,000 đ
	            	                    

        
        
        
        
        
                                
                                    27,990,000 đ
                            

                    
	    
	        

            
        


                                    
                                        
            
            
                        
            

        Kích cỡ màn hình14 inch    ModelLenovo ThinkPad T14    OptionThinkPad T14 Gen 4
        
    


                
                                                                        
                    
                                        






































    
                
        
                                                        
                                                    
                                            
                                        




    
                    
                    
                            


    
                            
        
        


    

            
                    
                                            





                    
                
                    
                                            





                    
                
                    
                                            





                    
                
                    
                                            





                    
                
                    
                                            





                    
                
                    
                                            





                    
                
                                            
                                                
                                                
                                                
                                                
                                                
                        

                                        		                    
                            
                        
                            

				                	                	                                
                    
    
        Giảm 17%
    

                        
	        
    
        Giảm Thêm 17%
    


        
                
            
    ThinkPad T14 Gen 4 - Intel Core i5-1340P / 16GB / 512GB / 14&quot; WUXGA

                 
                        
            
            
            	        	                	29,990,000 đ
	            	                    

        
        
        
        
        
                                
                                    24,990,000 đ
                            

                    
	    
	        

            
        
                
                                                        
                                
                    
                        Bảo Hành:
                    

                    						                            
                            
                                
                                                                    
                                   Bảo hành 1 năm
                                
                                                            


                            						                                                        
                                

                        
        
    

                                    
                                        
            
            
                        
            

        Kích cỡ màn hình14 inch    ModelLenovo ThinkPad T14    OptionThinkPad T14 Gen 4
        
    


                
                                                                        
                    
                                        






































    
                
        
                                                        
                        	                        
	                                Tạm hết hàng
	                        
                                            
                                        




    
                    
                    
                            


    
                            
        
        


    

            
                    
                                            





                    
                
                    
                                            





                    
                
                    
                                            





                    
                
                    
                                            





                    
                
                    
                                            





                    
                
                    
                                            





                    
                
                    
                                            





                    
                
                    
                                            





                    
                
                    
                                            





                    
                
                    
                                            





                    
                
                    
                                            





                    
                
                    
                                            





                    
                
                                            
                                                
                                                
                                                
                                                
                                                
                                                
                                                
                                                
                                                
                                                
                                                
                        

                                        		                    
                            
                        
                            

				                	                	                                
                    
    
        Giảm 12%
    

                        
	        
    
        Giảm Thêm 12%
    


        
                
            
    ThinkPad X1 Carbon Gen 11 - Intel Core i5-1335U / 16GB / 256GB SSD / 14&quot; WUXGA

                
        
        
                            
                    
                
                        
            
            
            	        	                	32,500,000 đ
	            	                    

        
        
        
        
        
                                
                                    28,500,000 đ
                            

                    
	    
	        

            
        


                                    
                                        
            
            
                        
            

        Kích cỡ màn hình14 inch    ModelLenovo ThinkPad X1 Carbon    OptionThinkPad X1 Carbon Gen 11
        
    


                
                                                                        
                    
                                        


	    
        
        	    
		
	


    
    
        

        
            


    
    
    


        
    

')]</value>
      <webElementGuid>d02fb43c-1b76-4273-a687-ba9312a69414</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
