<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>img__det_img_66920</name>
   <tag></tag>
   <elementGuidId>eac85d55-32e7-4d16-acd1-4b2a401c385f</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#det_img_66920</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//img[@id='det_img_66920']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>img</value>
      <webElementGuid>9af1131c-1f4d-43d4-86b9-dc2bc164d9f1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>ty-pict   cm-image lazyloaded</value>
      <webElementGuid>fcd525ad-1ddd-46e3-8ea2-89cdf86c6404</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>det_img_66920</value>
      <webElementGuid>4309af34-8e81-429a-b66d-2832c4934dcc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>https://zshop.vn/images/thumbnails/230/230/detailed/171/iphone-16_pro__10__aula-g1_j5t0-s6s.jpg</value>
      <webElementGuid>03888414-3272-49de-adcc-7df848445669</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>srcset</name>
      <type>Main</type>
      <value>https://zshop.vn/images/thumbnails/460/460/detailed/171/iphone-16_pro__10__aula-g1_j5t0-s6s.jpg 2x</value>
      <webElementGuid>11db9db1-89bf-4108-a33e-8b596ff938dc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-srcset</name>
      <type>Main</type>
      <value>https://zshop.vn/images/thumbnails/460/460/detailed/171/iphone-16_pro__10__aula-g1_j5t0-s6s.jpg 2x</value>
      <webElementGuid>4322708f-d4b3-474c-ade4-560be8ac1fb3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;det_img_66920&quot;)</value>
      <webElementGuid>91849825-4ca1-4a2f-9471-7ed0e33eac27</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//img[@id='det_img_66920']</value>
      <webElementGuid>3d7edcbd-0aef-4a37-9174-9b9c0cde7908</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='icons_66920']/div/div/div/div/a/img</value>
      <webElementGuid>0e233f98-b860-4102-857c-c467e041ed5b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:img</name>
      <type>Main</type>
      <value>//img[contains(@src,'https://zshop.vn/images/thumbnails/230/230/detailed/171/iphone-16_pro__10__aula-g1_j5t0-s6s.jpg')]</value>
      <webElementGuid>1d16bef7-c234-46c3-9646-b56002d79c18</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/div/div/div/div/a/img</value>
      <webElementGuid>22e5bca2-2602-4947-a2d8-9fed9323ad78</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//img[@id = 'det_img_66920' and @src = 'https://zshop.vn/images/thumbnails/230/230/detailed/171/iphone-16_pro__10__aula-g1_j5t0-s6s.jpg']</value>
      <webElementGuid>ed987eb8-7b21-45d6-8f3a-58e3e8ed57de</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
