<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>img_Ph kin my nh_det_img_21900059832</name>
   <tag></tag>
   <elementGuidId>8330ac14-dff7-4c3b-a27c-66f4a27872ab</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#det_img_21900059832</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//img[@id='det_img_21900059832']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>img</value>
      <webElementGuid>9ad37d07-739c-49b8-a9ef-b00ca13cde11</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>ty-pict   cm-image lazyloaded</value>
      <webElementGuid>88dacfd4-e2c7-435a-b0fc-70a495daeb71</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>det_img_21900059832</value>
      <webElementGuid>4fb0e60a-3244-48fb-8ce5-511cc8f875a5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>https://zshop.vn/images/thumbnails/230/230/detailed/171/CANON_R8B_21_4ls2-m118111.jpg</value>
      <webElementGuid>171b98db-5ce6-4463-ac9a-46a2a6dee9f5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-src</name>
      <type>Main</type>
      <value>https://zshop.vn/images/thumbnails/230/230/detailed/171/CANON_R8B_21_4ls2-m118111.jpg</value>
      <webElementGuid>3ba1102e-edfd-4a48-bbaa-9c11ba85b0c7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>srcset</name>
      <type>Main</type>
      <value>https://zshop.vn/images/thumbnails/460/460/detailed/171/CANON_R8B_21_4ls2-m118111.jpg 2x</value>
      <webElementGuid>4ae15693-e336-4202-a9cd-067b1d8dfeae</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-srcset</name>
      <type>Main</type>
      <value>https://zshop.vn/images/thumbnails/460/460/detailed/171/CANON_R8B_21_4ls2-m118111.jpg 2x</value>
      <webElementGuid>c0ce26e9-1067-4944-bd10-4b95df9ae801</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;det_img_21900059832&quot;)</value>
      <webElementGuid>9d145e63-55be-4be7-ad57-480a27e1650f</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//img[@id='det_img_21900059832']</value>
      <webElementGuid>fba51e6b-489e-43ee-809e-66447c202a79</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='scroll_list_219']/div/div/div/div/div/form/div/div[2]/a/img</value>
      <webElementGuid>ce2b1cf1-e42d-4830-8ee0-8f7ad62d60f6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:img</name>
      <type>Main</type>
      <value>//img[contains(@src,'https://zshop.vn/images/thumbnails/230/230/detailed/171/CANON_R8B_21_4ls2-m118111.jpg')]</value>
      <webElementGuid>c4b68d18-3903-4ae0-9db1-f7e3a4fa11e3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/div/div/div/div/form/div/div[2]/a/img</value>
      <webElementGuid>02632145-b58f-40ce-aae9-d1500396e6bb</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//img[@id = 'det_img_21900059832' and @src = 'https://zshop.vn/images/thumbnails/230/230/detailed/171/CANON_R8B_21_4ls2-m118111.jpg']</value>
      <webElementGuid>38dbd51b-6be5-44fe-b3d4-33aa3eb03226</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
