<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button_Gi</name>
   <tag></tag>
   <elementGuidId>5e81aaf0-f8a0-4715-b56b-3bda71993fda</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>button[name=&quot;dispatch[call_requests.request]&quot;]</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//button[@name='dispatch[call_requests.request]']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>52c7df2a-79eb-4d5e-b8dd-7154cb28f020</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>ty-btn__primary ty-btn__big cm-form-dialog-closer ty-btn ty-btn</value>
      <webElementGuid>16268392-72e8-438b-b4fd-39e087e9f8ab</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>submit</value>
      <webElementGuid>2e00cef3-2080-43dc-a175-fa7f67296166</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>dispatch[call_requests.request]</value>
      <webElementGuid>0889e2b1-63c8-4562-b234-7ae66351244c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Gửi</value>
      <webElementGuid>f23d61ff-82d3-4430-807c-407b8c321311</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;form_buy_now_with_one_click_66732&quot;)/div[@class=&quot;buttons-container buttons-container-picker&quot;]/button[@class=&quot;ty-btn__primary ty-btn__big cm-form-dialog-closer ty-btn ty-btn&quot;]</value>
      <webElementGuid>5a684f30-f83a-408f-a026-27d65382d18c</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//button[@name='dispatch[call_requests.request]']</value>
      <webElementGuid>2f74945c-6f10-4eea-ae8b-a22867e41020</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='form_buy_now_with_one_click_66732']/div[9]/button</value>
      <webElementGuid>a28a4f52-ddb7-44b6-a6f0-ecee4e32c778</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Xác nhận chống bot'])[4]/following::button[1]</value>
      <webElementGuid>0c921403-4121-4733-979e-144d5393a0c5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='E-mail'])[4]/following::button[1]</value>
      <webElementGuid>0001083e-c407-4701-8e7e-7d4f4a81d14c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[9]/button</value>
      <webElementGuid>fdcd460c-e5b0-47b4-9c0a-12ed7103ca78</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//button[@type = 'submit' and @name = 'dispatch[call_requests.request]' and (text() = 'Gửi' or . = 'Gửi')]</value>
      <webElementGuid>23b41067-77af-4f8e-b1a3-d24f1f0d9e63</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
