<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>img_Sp Ra Mt_det_img_18800066732</name>
   <tag></tag>
   <elementGuidId>e874306f-418c-45ab-9216-48f73b4a9e25</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#det_img_18800066732</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//img[@id='det_img_18800066732']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>img</value>
      <webElementGuid>f59104d0-f0af-4f75-9645-ed461b1cefd2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>ty-pict   cm-image lazyloaded</value>
      <webElementGuid>4b2d29f5-1fec-450b-aeb8-836ba57fb21a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>det_img_18800066732</value>
      <webElementGuid>489e4b14-77c2-477e-b802-20a2f34d6135</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>https://zshop.vn/images/thumbnails/230/230/detailed/174/FUJIFILM_X-M5_1-2_vw26-ef.jpg</value>
      <webElementGuid>a712f91c-8835-4c79-9f0d-a598462c29b1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-src</name>
      <type>Main</type>
      <value>https://zshop.vn/images/thumbnails/230/230/detailed/174/FUJIFILM_X-M5_1-2_vw26-ef.jpg</value>
      <webElementGuid>b96f2cbb-85b0-47ad-93f0-98255eb15995</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>srcset</name>
      <type>Main</type>
      <value>https://zshop.vn/images/thumbnails/460/460/detailed/174/FUJIFILM_X-M5_1-2_vw26-ef.jpg 2x</value>
      <webElementGuid>fe46651d-176a-4533-a01e-862a4c33b3f4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-srcset</name>
      <type>Main</type>
      <value>https://zshop.vn/images/thumbnails/460/460/detailed/174/FUJIFILM_X-M5_1-2_vw26-ef.jpg 2x</value>
      <webElementGuid>15629f30-7f32-40b5-99dd-c7139ab26a4b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;det_img_18800066732&quot;)</value>
      <webElementGuid>d018da60-9cf5-4d74-97c6-032dda895a51</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//img[@id='det_img_18800066732']</value>
      <webElementGuid>b47786f4-4507-49d0-accb-9664cfea0385</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='scroll_list_188']/div/div/div/div/div/form/div/div[2]/a/img</value>
      <webElementGuid>05762dd6-380c-4348-8001-57c25e373d78</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:img</name>
      <type>Main</type>
      <value>//img[contains(@src,'https://zshop.vn/images/thumbnails/230/230/detailed/174/FUJIFILM_X-M5_1-2_vw26-ef.jpg')]</value>
      <webElementGuid>4d6308ff-c5a7-471b-9746-3659808ab35b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//form/div/div[2]/a/img</value>
      <webElementGuid>becb0d32-1d14-459e-b840-a538929bdc9b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//img[@id = 'det_img_18800066732' and @src = 'https://zshop.vn/images/thumbnails/230/230/detailed/174/FUJIFILM_X-M5_1-2_vw26-ef.jpg']</value>
      <webElementGuid>208b37b1-ac0c-429f-b234-e93102b47de9</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
