<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_H v Tn ca bn_call_dataname</name>
   <tag></tag>
   <elementGuidId>d41f4f61-b28a-4ff6-ab86-d21c6c5362dc</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#call_data_buy_now_with_one_click_66732_name</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='call_data_buy_now_with_one_click_66732_name']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>cf49ff71-1864-48c5-8a31-30a93c79a309</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>call_data_buy_now_with_one_click_66732_name</value>
      <webElementGuid>9fff4f24-494a-4113-9421-2ddf74da9589</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>size</name>
      <type>Main</type>
      <value>50</value>
      <webElementGuid>ff3f198d-161a-4b36-8460-38b18ef3cc86</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>ty-input-text-full</value>
      <webElementGuid>0b637738-c3cc-4a82-ab69-7ce5fdd8d9de</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>364eced1-d3af-4b83-8739-7f14e5b91440</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>call_data[name]</value>
      <webElementGuid>c4de22cb-51bb-403b-ad19-3c5c907a11f0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;call_data_buy_now_with_one_click_66732_name&quot;)</value>
      <webElementGuid>fd7b1988-64eb-4d76-a49c-0443b38cb3a6</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='call_data_buy_now_with_one_click_66732_name']</value>
      <webElementGuid>994474eb-7da4-477e-8fc2-b31cef7c5090</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='form_buy_now_with_one_click_66732']/div[2]/input</value>
      <webElementGuid>d3b79485-0ca7-425a-b71a-0c6728828d30</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/form/div[2]/input</value>
      <webElementGuid>c7c576b4-dd30-4ca8-a6a4-f2e711f3c31a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'call_data_buy_now_with_one_click_66732_name' and @type = 'text' and @name = 'call_data[name]']</value>
      <webElementGuid>002f2efa-4b32-4aa6-8ca6-1a50c66719f2</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
