<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_in thoi_call_dataphone</name>
   <tag></tag>
   <elementGuidId>27b569d2-76a6-4b45-95ab-e4a27004892c</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#call_data_buy_now_with_one_click_66732_phone</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='call_data_buy_now_with_one_click_66732_phone']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>10ef70aa-ee3e-4dbd-9f1a-36f5ea452db2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>call_data_buy_now_with_one_click_66732_phone</value>
      <webElementGuid>9dce7dc2-e36d-438b-b1bc-fcca67ebec99</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>ty-input-text-full cm-mask-phone ty-inputmask-bdi</value>
      <webElementGuid>2a6f2be4-47eb-463d-aaa8-c86a7d709c66</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>size</name>
      <type>Main</type>
      <value>50</value>
      <webElementGuid>c227112b-0240-4b77-a1bf-1c3a3e9eafe2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>87b966b5-7330-416f-8823-7986c5e830cf</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>call_data[phone]</value>
      <webElementGuid>29f138c5-24b1-4eaa-bf04-8b7cb51f48d4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-enable-custom-mask</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>084337e9-acff-4ebb-bfff-9a92f79fd447</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;call_data_buy_now_with_one_click_66732_phone&quot;)</value>
      <webElementGuid>6ca2416f-23c3-449d-a61c-c0ccb24f2e57</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='call_data_buy_now_with_one_click_66732_phone']</value>
      <webElementGuid>7bc183f0-abd9-43f1-a3ff-f70712a806d9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='form_buy_now_with_one_click_66732']/div[3]/input</value>
      <webElementGuid>d759e30f-ffd6-4d4f-a1b6-028ce1d4c10f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/div[2]/form/div[3]/input</value>
      <webElementGuid>4c0c545d-c501-45f6-bd2f-869346e047f3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'call_data_buy_now_with_one_click_66732_phone' and @type = 'text' and @name = 'call_data[phone]']</value>
      <webElementGuid>642ad4f6-cdba-474a-9081-8cc8d138343c</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
