<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_E-mail_call_dataemail2</name>
   <tag></tag>
   <elementGuidId>9f4256f5-37c7-44aa-89d7-8bed2c16dc78</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#call_data_buy_now_with_one_click_66732_email2</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='call_data_buy_now_with_one_click_66732_email2']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>4d0226cd-c1a6-4f81-b528-7566ab12a0f2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>call_data_buy_now_with_one_click_66732_email2</value>
      <webElementGuid>f203e501-9ad9-4c56-8df9-4dfeb82b7367</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>ty-input-text-full</value>
      <webElementGuid>0d2c32ca-acd1-4efd-9e7a-287beac820b2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>size</name>
      <type>Main</type>
      <value>50</value>
      <webElementGuid>3add2331-5c86-4e27-8fe6-1beb396bffd1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>df964cc9-c295-4d31-8b14-977a1c9f8736</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>call_data[email2]</value>
      <webElementGuid>83966744-6261-48c6-9c9c-559a455e7662</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;call_data_buy_now_with_one_click_66732_email2&quot;)</value>
      <webElementGuid>5190bf26-f849-4a2a-b919-2af30a098358</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='call_data_buy_now_with_one_click_66732_email2']</value>
      <webElementGuid>4ac848cf-3221-4491-8f56-5bfddce8928e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='form_buy_now_with_one_click_66732']/div[5]/input</value>
      <webElementGuid>75e4363f-2ae9-4581-bf7f-7cf6e5858394</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[5]/input</value>
      <webElementGuid>222052fa-6da1-455b-9808-eef0a85904da</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'call_data_buy_now_with_one_click_66732_email2' and @type = 'text' and @name = 'call_data[email2]']</value>
      <webElementGuid>ad705bab-e1db-40b4-9fa1-782040d4bd17</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
