<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_a ch_call_dataaddress</name>
   <tag></tag>
   <elementGuidId>4c53fc59-c980-40b4-9ace-ef9e8e31478e</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#call_data_buy_now_with_one_click_66732_address</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='call_data_buy_now_with_one_click_66732_address']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>789b399a-1037-4729-bf2b-d6a66f99155c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>call_data_buy_now_with_one_click_66732_address</value>
      <webElementGuid>2fe3adee-745c-4192-ab2e-3a82e0e2a7d2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>ty-input-text-full</value>
      <webElementGuid>8eb309f2-4b4d-4a73-8a54-2375ac82b3c9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>size</name>
      <type>Main</type>
      <value>50</value>
      <webElementGuid>8b05a068-c205-42ed-a6e8-400a72815aaf</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>fdcce93f-f74c-45a5-9ddb-29993b6fb760</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>call_data[address]</value>
      <webElementGuid>a7ba0986-c12c-4fdb-a6ec-e6f7b54976d7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;call_data_buy_now_with_one_click_66732_address&quot;)</value>
      <webElementGuid>bc2b0e69-ea3f-415d-87d1-a1161c75adb9</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='call_data_buy_now_with_one_click_66732_address']</value>
      <webElementGuid>364b47f4-64da-4803-ab08-7871a7a6350f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='form_buy_now_with_one_click_66732']/div[4]/input</value>
      <webElementGuid>3e42f0a1-dddb-48d5-acf5-bda267b193ff</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/form/div[4]/input</value>
      <webElementGuid>60ae878d-8595-454c-87f1-66a1a3d5f06f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'call_data_buy_now_with_one_click_66732_address' and @type = 'text' and @name = 'call_data[address]']</value>
      <webElementGuid>d3aa869b-aa6a-4a83-8129-2d35812efd0d</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
