<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Xc nhn chng bot_native_captcha_response</name>
   <tag></tag>
   <elementGuidId>53e954a6-ff19-4995-a835-aecb8c1e6820</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#recaptcha_675d972a6e586</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='recaptcha_675d972a6e586']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>cd011cc0-d3f4-4c58-a345-87d141225db6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>d03acec0-fc00-404d-94e2-d1442fd54703</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>recaptcha_675d972a6e586</value>
      <webElementGuid>e3e6d515-7b21-4d37-9a3f-a277c854dfc2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>input-text native-captcha__answer form-control</value>
      <webElementGuid>65599f97-c8dd-46a1-9b31-4bfa75b5bca6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>native_captcha_response</value>
      <webElementGuid>4ca013df-7ab9-4a0b-8558-f0b06d6c7838</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>autocomplete</name>
      <type>Main</type>
      <value>off</value>
      <webElementGuid>83c1634b-b89e-43bd-810f-d879e5f1a6ac</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Xác nhận chống bot</value>
      <webElementGuid>7c4efabf-6083-4e02-8631-bc66994b93ae</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;recaptcha_675d972a6e586&quot;)</value>
      <webElementGuid>1676e077-23f0-4631-97f8-81175b468fc7</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='recaptcha_675d972a6e586']</value>
      <webElementGuid>583d1b3b-5cce-44f2-bbe5-cd2460682346</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='form_buy_now_with_one_click_66732']/div[7]/input</value>
      <webElementGuid>3738a5b5-e7ca-471a-a86a-10d065857da8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[7]/input</value>
      <webElementGuid>12c9a598-edb6-4c34-ae7e-4a0bd18b36b0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @id = 'recaptcha_675d972a6e586' and @name = 'native_captcha_response' and @placeholder = 'Xác nhận chống bot']</value>
      <webElementGuid>84a1fcf6-d0e1-4387-8b0e-e2dfdf31af2f</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
