<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input__right_254_1</name>
   <tag></tag>
   <elementGuidId>efe20c00-7893-4881-950b-b5ab3aab7bf1</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#slider_254_1_right</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='slider_254_1_right']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>e1081a16-2360-4590-89d6-417cef31d3b8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>181deefc-710a-4d46-977e-8818f356fbbe</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>ty-price-slider__input-text</value>
      <webElementGuid>47bafef8-46c1-409f-9e6f-3af2989f49dd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>slider_254_1_right</value>
      <webElementGuid>654003d4-fb2d-436b-85e2-a1acbb192866</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>right_254_1</value>
      <webElementGuid>a78d5613-9676-41c7-b62f-62cb466fb6db</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>49990000</value>
      <webElementGuid>e8e7ee6e-df76-4a3d-b2d7-e6eff39dc2e1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-ca-previous-value</name>
      <type>Main</type>
      <value>49990000</value>
      <webElementGuid>68fcdd23-2834-4d0f-93a7-0e9601b6e4f5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;slider_254_1_right&quot;)</value>
      <webElementGuid>3966479d-c12b-4da2-880e-39a17c7504e7</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='slider_254_1_right']</value>
      <webElementGuid>9070bc04-6f0e-4b1d-88be-16590783c2fd</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='content_254_1']/p/bdi[2]/input</value>
      <webElementGuid>a7e5a787-a41f-4ab2-862b-60b3876a372a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//bdi[2]/input</value>
      <webElementGuid>3431d56b-ec8f-4340-a5c3-58363dc72d66</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @id = 'slider_254_1_right' and @name = 'right_254_1']</value>
      <webElementGuid>66983c3a-929e-4815-942d-dca232be2bc9</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
