<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>img_Sp Ra Mt_det_img_18800066732</name>
   <tag></tag>
   <elementGuidId>5e753460-4e4b-49f8-b8f4-97c450301493</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#det_img_18800066732</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//img[@id='det_img_18800066732']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>img</value>
      <webElementGuid>57287557-b402-4bc6-a09e-ba6447ffd10b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>ty-pict   cm-image ls-is-cached lazyloaded</value>
      <webElementGuid>5fefe87a-e8e1-4842-b3e4-13c2447c00c7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>det_img_18800066732</value>
      <webElementGuid>fb3d569a-4d63-4fda-a843-47bb392212c7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>https://zshop.vn/images/thumbnails/230/230/detailed/174/FUJIFILM_X-M5_1-2_vw26-ef.jpg</value>
      <webElementGuid>b3186f21-5571-4f4d-831a-bc0d7c786006</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-src</name>
      <type>Main</type>
      <value>https://zshop.vn/images/thumbnails/230/230/detailed/174/FUJIFILM_X-M5_1-2_vw26-ef.jpg</value>
      <webElementGuid>8a6d3d9a-7b7b-4ca6-81e4-3ebda4c4d2cf</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>srcset</name>
      <type>Main</type>
      <value>https://zshop.vn/images/thumbnails/460/460/detailed/174/FUJIFILM_X-M5_1-2_vw26-ef.jpg 2x</value>
      <webElementGuid>6433e94c-099c-458e-83a9-73320d6b0a79</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-srcset</name>
      <type>Main</type>
      <value>https://zshop.vn/images/thumbnails/460/460/detailed/174/FUJIFILM_X-M5_1-2_vw26-ef.jpg 2x</value>
      <webElementGuid>4b7961dc-4efe-440d-8515-63bb5f5ba95d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;det_img_18800066732&quot;)</value>
      <webElementGuid>f9950f89-0130-43bc-9e38-f87611444743</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//img[@id='det_img_18800066732']</value>
      <webElementGuid>716e9685-e567-4508-a1b2-8c3b5d233bdf</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='scroll_list_188']/div/div/div/div/div/form/div/div[2]/a/img</value>
      <webElementGuid>333efbb5-ba91-489b-909f-ed3da128df95</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:img</name>
      <type>Main</type>
      <value>//img[contains(@src,'https://zshop.vn/images/thumbnails/230/230/detailed/174/FUJIFILM_X-M5_1-2_vw26-ef.jpg')]</value>
      <webElementGuid>4d5bd2cb-cab0-474c-bad5-9d453f51b23f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//form/div/div[2]/a/img</value>
      <webElementGuid>fa5f4a89-aa23-4d45-a654-91d3d48e3d27</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//img[@id = 'det_img_18800066732' and @src = 'https://zshop.vn/images/thumbnails/230/230/detailed/174/FUJIFILM_X-M5_1-2_vw26-ef.jpg']</value>
      <webElementGuid>4b932af2-7fcb-4fb0-b00c-ae837111d7da</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
