<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>img_Apple_det_img_66823</name>
   <tag></tag>
   <elementGuidId>f11f4b67-64d5-4e70-b9a0-e3e59ea429c1</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#det_img_66823</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//img[@id='det_img_66823']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>img</value>
      <webElementGuid>724ee358-6ea1-45e8-b286-d3a100bbbc0a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>ty-pict   cm-image lazyloaded</value>
      <webElementGuid>273cc848-546d-46bb-a4d6-39a336ca6b92</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>det_img_66823</value>
      <webElementGuid>1e7ae322-d409-4a53-9ccc-7e664c83b91e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>https://zshop.vn/images/thumbnails/230/230/detailed/170/iphone-16__2__3uff-oq.jpg</value>
      <webElementGuid>1122e7ef-88c8-4d36-82c0-5167fee96960</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>srcset</name>
      <type>Main</type>
      <value>https://zshop.vn/images/thumbnails/460/460/detailed/170/iphone-16__2__3uff-oq.jpg 2x</value>
      <webElementGuid>76e8f074-aaf8-4fd9-a865-34814af10534</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-srcset</name>
      <type>Main</type>
      <value>https://zshop.vn/images/thumbnails/460/460/detailed/170/iphone-16__2__3uff-oq.jpg 2x</value>
      <webElementGuid>f956adba-226d-48fd-ba24-5f2e5904a9b9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;det_img_66823&quot;)</value>
      <webElementGuid>df2693de-8595-4698-9cc9-17fe77383500</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//img[@id='det_img_66823']</value>
      <webElementGuid>add86965-2ee7-4b95-828c-880599a2bc29</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='icons_66823']/div/div/div/div/a/img</value>
      <webElementGuid>7303e3d7-57bf-4aeb-959d-5fb46ecc16d3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:img</name>
      <type>Main</type>
      <value>//img[contains(@src,'https://zshop.vn/images/thumbnails/230/230/detailed/170/iphone-16__2__3uff-oq.jpg')]</value>
      <webElementGuid>a7e8c52e-f6a0-436a-8b55-59c967f9dceb</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/form/div/div[2]/div[2]/div/div/div/div/div/a/img</value>
      <webElementGuid>d1a7809a-607e-474c-93f1-627eab8f296f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//img[@id = 'det_img_66823' and @src = 'https://zshop.vn/images/thumbnails/230/230/detailed/170/iphone-16__2__3uff-oq.jpg']</value>
      <webElementGuid>c958c5c7-8ad0-4de7-9b8d-60445631483e</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
