<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>img_Sp Ra Mt_det_img_18800066732</name>
   <tag></tag>
   <elementGuidId>8db5e1b5-7bbe-4b18-8aa4-051a3fbdc671</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#det_img_18800066732</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//img[@id='det_img_18800066732']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>img</value>
      <webElementGuid>f8c5456e-e3ac-4399-a700-a17a7205bf1e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>ty-pict   cm-image lazyloaded</value>
      <webElementGuid>85dadb98-4fb9-4e9f-94e1-27e92b7baa27</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>det_img_18800066732</value>
      <webElementGuid>e3b977de-e725-472f-a6be-eb31640c0634</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>https://zshop.vn/images/thumbnails/230/230/detailed/174/FUJIFILM_X-M5_1-2_vw26-ef.jpg</value>
      <webElementGuid>e1535c68-6b59-4666-b444-a100ee0603bb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-src</name>
      <type>Main</type>
      <value>https://zshop.vn/images/thumbnails/230/230/detailed/174/FUJIFILM_X-M5_1-2_vw26-ef.jpg</value>
      <webElementGuid>83bb8aab-126b-48eb-ac75-ce23e54a7779</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>srcset</name>
      <type>Main</type>
      <value>https://zshop.vn/images/thumbnails/460/460/detailed/174/FUJIFILM_X-M5_1-2_vw26-ef.jpg 2x</value>
      <webElementGuid>09fcd06e-099b-469c-b7d5-f4356f2b2751</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-srcset</name>
      <type>Main</type>
      <value>https://zshop.vn/images/thumbnails/460/460/detailed/174/FUJIFILM_X-M5_1-2_vw26-ef.jpg 2x</value>
      <webElementGuid>eeb705b5-fb52-44d4-ab52-d93b9c07c917</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;det_img_18800066732&quot;)</value>
      <webElementGuid>5afcf1c7-78a0-4459-8d33-3b9dd0d0bfb8</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//img[@id='det_img_18800066732']</value>
      <webElementGuid>3cf6bf61-7a9b-440a-aa5e-a3a13dc1fed2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='scroll_list_188']/div/div/div/div/div/form/div/div[2]/a/img</value>
      <webElementGuid>6ef3cf00-d8c8-428c-81db-6057722860e8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:img</name>
      <type>Main</type>
      <value>//img[contains(@src,'https://zshop.vn/images/thumbnails/230/230/detailed/174/FUJIFILM_X-M5_1-2_vw26-ef.jpg')]</value>
      <webElementGuid>29985979-75da-494f-8347-6634c0ee0c69</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//form/div/div[2]/a/img</value>
      <webElementGuid>4b0ad6b7-3bce-4b10-9dbc-00aab5e05bc3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//img[@id = 'det_img_18800066732' and @src = 'https://zshop.vn/images/thumbnails/230/230/detailed/174/FUJIFILM_X-M5_1-2_vw26-ef.jpg']</value>
      <webElementGuid>e9372cf0-9a33-4ef9-9748-dc5d00fde934</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
