<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>img_Tng gi_det_img_1172020233</name>
   <tag></tag>
   <elementGuidId>77c15853-d8c7-4275-a6e8-9f9cf3e739d2</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#det_img_1172020233</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//img[@id='det_img_1172020233']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>img</value>
      <webElementGuid>0c1773ec-cfda-4e9a-b0e7-306e919a1431</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>ty-pict   cm-image ls-is-cached lazyloaded</value>
      <webElementGuid>3eb51e01-baec-4422-9b8f-4b1fcfd8e83c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>det_img_1172020233</value>
      <webElementGuid>e2abcfee-43d6-4e03-8cbe-ba633afa2105</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>https://zshop.vn/images/thumbnails/230/230/detailed/170/iphone-16__2__3uff-oq.jpg</value>
      <webElementGuid>517ab7f5-21ff-409c-8f98-79943d591cd7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-src</name>
      <type>Main</type>
      <value>https://zshop.vn/images/thumbnails/230/230/detailed/170/iphone-16__2__3uff-oq.jpg</value>
      <webElementGuid>2785938c-6847-4664-8404-ba814ab479df</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>srcset</name>
      <type>Main</type>
      <value>https://zshop.vn/images/thumbnails/460/460/detailed/170/iphone-16__2__3uff-oq.jpg 2x</value>
      <webElementGuid>6f15d018-0835-4c71-b18e-843af5af74ac</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-srcset</name>
      <type>Main</type>
      <value>https://zshop.vn/images/thumbnails/460/460/detailed/170/iphone-16__2__3uff-oq.jpg 2x</value>
      <webElementGuid>5181649e-3b97-479a-aa26-8e6e53118f1d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;det_img_1172020233&quot;)</value>
      <webElementGuid>14326972-ac88-473b-bf41-cd2fc58c7915</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//img[@id='det_img_1172020233']</value>
      <webElementGuid>e0e3de9f-526d-431f-a0c7-4ab032ff1bac</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='product_image_update_1172020233']/a/img</value>
      <webElementGuid>b562a747-1f62-4bb2-be62-0974377368e0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:img</name>
      <type>Main</type>
      <value>//img[contains(@src,'https://zshop.vn/images/thumbnails/230/230/detailed/170/iphone-16__2__3uff-oq.jpg')]</value>
      <webElementGuid>4a47b8ba-9a8a-4ac1-a016-07c08eac5f43</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//td/div/a/img</value>
      <webElementGuid>fa6fa4ca-ece8-4e21-9609-f3c8cb4cc7ca</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//img[@id = 'det_img_1172020233' and @src = 'https://zshop.vn/images/thumbnails/230/230/detailed/170/iphone-16__2__3uff-oq.jpg']</value>
      <webElementGuid>78071c1b-3840-4381-bd70-e2dcc8cfa3e8</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
