<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>span_Xoa_gio_hang</name>
   <tag></tag>
   <elementGuidId>cf58dd3d-2a5c-48e0-9fed-e5658067dde9</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>a.ty-btn.ty-btn__tertiary.text-button > span</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='tygh_main_container']/div[3]/div/div[2]/div/div/div/div/div[2]/div/a[2]/span</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>5f27f0d7-7df2-4b01-85d1-9ad62ceef802</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Xóa giỏ hàng</value>
      <webElementGuid>884c93a0-1d05-453f-afcd-803e2700ae1d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;tygh_main_container&quot;)/div[@class=&quot;tygh-content clearfix&quot;]/div[@class=&quot;container-fluid  content-grid ypi-cart-grid&quot;]/div[@class=&quot;container-fluid-row main-content-grid&quot;]/div[@class=&quot;row-fluid&quot;]/div[@class=&quot;span16 main-content-grid&quot;]/div[@class=&quot;ty-mainbox-container clearfix&quot;]/div[@class=&quot;ty-mainbox-body&quot;]/div[@class=&quot;buttons-container ty-cart-content__bottom-buttons clearfix&quot;]/div[@class=&quot;ty-float-left ty-cart-content__left-buttons&quot;]/a[@class=&quot;ty-btn ty-btn__tertiary text-button&quot;]/span[1]</value>
      <webElementGuid>b95bdff4-2f34-4b9f-be58-68939415782b</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='tygh_main_container']/div[3]/div/div[2]/div/div/div/div/div[2]/div/a[2]/span</value>
      <webElementGuid>ab2a2ec5-1246-41a4-9ee4-e158f0f53198</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Tiếp tục mua hàng'])[2]/following::span[1]</value>
      <webElementGuid>e5df9d9a-1c4e-4293-9152-2c27c20194e7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='đ'])[4]/following::span[2]</value>
      <webElementGuid>46577b29-2992-4e6a-8265-f24a12ee3750</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Tiến hành thanh toán'])[2]/preceding::span[1]</value>
      <webElementGuid>67700fae-e01f-4e47-869c-6383dc04d288</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Xóa giỏ hàng']/parent::*</value>
      <webElementGuid>7f6dd900-ac74-4b51-9bd4-9d8a1c0df0da</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div/a[2]/span</value>
      <webElementGuid>ea041cf2-7e28-463a-8807-c6b083fae258</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//span[(text() = 'Xóa giỏ hàng' or . = 'Xóa giỏ hàng')]</value>
      <webElementGuid>c18e4754-d88e-436e-af2a-5c617ddad2da</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
