<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_Thit lp li</name>
   <tag></tag>
   <elementGuidId>199bef20-152a-4e30-a930-ac04c447c229</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>a.ty-btn.ty-product-filters__reset-button.cm-ajax.cm-ajax-full-render.cm-history</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='product_filters_254']/div/div[10]/a</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>ab31b480-a080-44ea-b60d-70562e1bb769</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>https://zshop.vn/khuyen-mai/</value>
      <webElementGuid>e5714d45-f0a8-4da0-9280-f45ee0503230</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>rel</name>
      <type>Main</type>
      <value>nofollow</value>
      <webElementGuid>93d34c47-a352-44d0-9858-b2146b00522e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>ty-btn ty-product-filters__reset-button cm-ajax cm-ajax-full-render cm-history</value>
      <webElementGuid>55ef54a9-e336-41d0-89b1-be48cdd83269</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-ca-event</name>
      <type>Main</type>
      <value>ce.filtersinit</value>
      <webElementGuid>7e139d18-b552-4546-a58d-bc5595bc364d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-ca-scroll</name>
      <type>Main</type>
      <value>.ty-mainbox-title</value>
      <webElementGuid>07fff94a-ce65-434d-bec4-94d1e9cf785f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-ca-target-id</name>
      <type>Main</type>
      <value>product_filters_*,selected_filters_*,products_search_*,category_products_*,currencies_*,languages_*,abt__yt_subcategories_*,product_features_*</value>
      <webElementGuid>0508d35b-1daf-41c7-90f4-b7ab8c5be14a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value> Thiết lập lại</value>
      <webElementGuid>2559e6ae-2e1c-438b-b5b7-2f6196fca9d7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;product_filters_254&quot;)/div[@class=&quot;ty-product-filters__wrapper&quot;]/div[@class=&quot;ty-product-filters__tools clearfix&quot;]/a[@class=&quot;ty-btn ty-product-filters__reset-button cm-ajax cm-ajax-full-render cm-history&quot;]</value>
      <webElementGuid>ff48f682-a733-4c21-afda-d432c8d4f8db</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='product_filters_254']/div/div[10]/a</value>
      <webElementGuid>997334ba-1d83-42cc-8167-7c068da140b8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>//a[contains(text(),'Thiết lập lại')]</value>
      <webElementGuid>947b17d3-a8b6-46c2-a721-a7ee0a19bfeb</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='RAM - Bộ Nhớ (1)'])[1]/following::a[1]</value>
      <webElementGuid>93e1ec01-6371-4eba-9bff-b6437bb3b66e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='X1 Nano Gen 1'])[1]/following::a[2]</value>
      <webElementGuid>23d62db1-3779-4eec-8e2f-dc367b1443b6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)=''])[1]/preceding::a[1]</value>
      <webElementGuid>73ce96e4-42c4-4935-8d4e-a0d3047a044f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Khuyến Mãi'])[1]/preceding::a[2]</value>
      <webElementGuid>c356aad2-35a5-49d9-bbc8-8fd1ed6d321e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Thiết lập lại']/parent::*</value>
      <webElementGuid>b90c43fe-1cfa-478d-9d28-c407881baf10</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>(//a[contains(@href, 'https://zshop.vn/khuyen-mai/')])[6]</value>
      <webElementGuid>7921cdd0-6f69-4fcf-925d-988196f4be25</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/div/div/div[10]/a</value>
      <webElementGuid>5667df3e-72fc-46e2-a27b-1e203b01655d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = 'https://zshop.vn/khuyen-mai/' and (text() = ' Thiết lập lại' or . = ' Thiết lập lại')]</value>
      <webElementGuid>ac1538de-8a22-40e7-873a-8d6d11651f54</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
